"""team table

Revision ID: 3d0f4c98166c
Revises: b6c5ddfd5211
Create Date: 2018-09-20 19:07:54.622943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d0f4c98166c'
down_revision = 'b6c5ddfd5211'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_name', sa.String(length=64), nullable=True),
    sa.Column('team_point', sa.Integer(), nullable=True),
    sa.Column('team_desc', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_team_desc'), 'team', ['team_desc'], unique=False)
    op.create_index(op.f('ix_team_team_name'), 'team', ['team_name'], unique=False)
    op.create_index(op.f('ix_team_team_point'), 'team', ['team_point'], unique=False)
    op.create_table('team_and_pieces',
    sa.Column('piece_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['piece_id'], ['pieces.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('piece_id', 'team_id')
    )
    op.drop_table('pieces_and_keywords')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pieces_and_keywords',
    sa.Column('piece_id', sa.INTEGER(), nullable=False),
    sa.Column('keyword_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.id'], ),
    sa.ForeignKeyConstraint(['piece_id'], ['pieces.id'], ),
    sa.PrimaryKeyConstraint('piece_id', 'keyword_id')
    )
    op.drop_table('team_and_pieces')
    op.drop_index(op.f('ix_team_team_point'), table_name='team')
    op.drop_index(op.f('ix_team_team_name'), table_name='team')
    op.drop_index(op.f('ix_team_team_desc'), table_name='team')
    op.drop_table('team')
    # ### end Alembic commands ###
