"""tabelas refeitas

Revision ID: a13f22d1fa1e
Revises: 
Create Date: 2018-06-06 23:11:19.325533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a13f22d1fa1e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('colle_name', sa.String(length=64), nullable=True),
    sa.Column('colle_initials', sa.String(length=10), nullable=True),
    sa.Column('colle_age', sa.String(length=60), nullable=True),
    sa.Column('colle_releasedate', sa.String(length=10), nullable=True),
    sa.Column('colle_piecequantity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collection_colle_age'), 'collection', ['colle_age'], unique=True)
    op.create_index(op.f('ix_collection_colle_initials'), 'collection', ['colle_initials'], unique=False)
    op.create_index(op.f('ix_collection_colle_name'), 'collection', ['colle_name'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('pieces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('piece_name', sa.String(length=64), nullable=True),
    sa.Column('piece_real_name', sa.String(length=64), nullable=True),
    sa.Column('piece_number', sa.String(), nullable=True),
    sa.Column('piece_trait', sa.String(length=300), nullable=True),
    sa.Column('piece_improved_target', sa.String(length=50), nullable=True),
    sa.Column('piece_improved_mov', sa.String(length=50), nullable=True),
    sa.Column('piece_mov_type', sa.String(length=20), nullable=True),
    sa.Column('piece_atk_type', sa.String(length=20), nullable=True),
    sa.Column('piece_def_type', sa.String(length=20), nullable=True),
    sa.Column('piece_dam_type', sa.String(length=20), nullable=True),
    sa.Column('piece_range', sa.Integer(), nullable=True),
    sa.Column('piece_bolts', sa.Integer(), nullable=True),
    sa.Column('collection_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pieces_piece_atk_type'), 'pieces', ['piece_atk_type'], unique=False)
    op.create_index(op.f('ix_pieces_piece_dam_type'), 'pieces', ['piece_dam_type'], unique=False)
    op.create_index(op.f('ix_pieces_piece_def_type'), 'pieces', ['piece_def_type'], unique=False)
    op.create_index(op.f('ix_pieces_piece_improved_mov'), 'pieces', ['piece_improved_mov'], unique=False)
    op.create_index(op.f('ix_pieces_piece_improved_target'), 'pieces', ['piece_improved_target'], unique=False)
    op.create_index(op.f('ix_pieces_piece_mov_type'), 'pieces', ['piece_mov_type'], unique=False)
    op.create_index(op.f('ix_pieces_piece_name'), 'pieces', ['piece_name'], unique=False)
    op.create_index(op.f('ix_pieces_piece_number'), 'pieces', ['piece_number'], unique=False)
    op.create_index(op.f('ix_pieces_piece_real_name'), 'pieces', ['piece_real_name'], unique=False)
    op.create_index(op.f('ix_pieces_piece_trait'), 'pieces', ['piece_trait'], unique=False)
    op.create_table('dial__attack',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datk_pos1', sa.String(length=2), nullable=True),
    sa.Column('datk_pos2', sa.String(length=2), nullable=True),
    sa.Column('datk_pos3', sa.String(length=2), nullable=True),
    sa.Column('datk_pos4', sa.String(length=2), nullable=True),
    sa.Column('datk_pos5', sa.String(length=2), nullable=True),
    sa.Column('datk_pos6', sa.String(length=2), nullable=True),
    sa.Column('datk_pos7', sa.String(length=2), nullable=True),
    sa.Column('datk_pos8', sa.String(length=2), nullable=True),
    sa.Column('datk_pos9', sa.String(length=2), nullable=True),
    sa.Column('datk_pos10', sa.String(length=2), nullable=True),
    sa.Column('datk_pos11', sa.String(length=2), nullable=True),
    sa.Column('datk_pos12', sa.String(length=2), nullable=True),
    sa.Column('datk_cor1', sa.String(length=30), nullable=True),
    sa.Column('datk_cor2', sa.String(length=30), nullable=True),
    sa.Column('datk_cor3', sa.String(length=30), nullable=True),
    sa.Column('datk_cor4', sa.String(length=30), nullable=True),
    sa.Column('datk_cor5', sa.String(length=30), nullable=True),
    sa.Column('datk_cor6', sa.String(length=30), nullable=True),
    sa.Column('datk_cor7', sa.String(length=30), nullable=True),
    sa.Column('datk_cor8', sa.String(length=30), nullable=True),
    sa.Column('datk_cor9', sa.String(length=30), nullable=True),
    sa.Column('datk_cor10', sa.String(length=30), nullable=True),
    sa.Column('datk_cor11', sa.String(length=30), nullable=True),
    sa.Column('datk_cor12', sa.String(length=30), nullable=True),
    sa.Column('pieces_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pieces_id'], ['pieces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dial__attack_datk_cor1'), 'dial__attack', ['datk_cor1'], unique=False)
    op.create_index(op.f('ix_dial__attack_datk_cor10'), 'dial__attack', ['datk_cor10'], unique=False)
    op.create_index(op.f('ix_dial__attack_datk_cor11'), 'dial__attack', ['datk_cor11'], unique=False)
    op.create_index(op.f('ix_dial__attack_datk_cor12'), 'dial__attack', ['datk_cor12'], unique=False)
    op.create_index(op.f('ix_dial__attack_datk_cor2'), 'dial__attack', ['datk_cor2'], unique=False)
    op.create_index(op.f('ix_dial__attack_datk_cor3'), 'dial__attack', ['datk_cor3'], unique=False)
    op.create_index(op.f('ix_dial__attack_datk_cor4'), 'dial__attack', ['datk_cor4'], unique=False)
    op.create_index(op.f('ix_dial__attack_datk_cor5'), 'dial__attack', ['datk_cor5'], unique=False)
    op.create_index(op.f('ix_dial__attack_datk_cor6'), 'dial__attack', ['datk_cor6'], unique=False)
    op.create_index(op.f('ix_dial__attack_datk_cor7'), 'dial__attack', ['datk_cor7'], unique=False)
    op.create_index(op.f('ix_dial__attack_datk_cor8'), 'dial__attack', ['datk_cor8'], unique=False)
    op.create_index(op.f('ix_dial__attack_datk_cor9'), 'dial__attack', ['datk_cor9'], unique=False)
    op.create_index(op.f('ix_dial__attack_datk_pos1'), 'dial__attack', ['datk_pos1'], unique=False)
    op.create_index(op.f('ix_dial__attack_datk_pos10'), 'dial__attack', ['datk_pos10'], unique=False)
    op.create_index(op.f('ix_dial__attack_datk_pos11'), 'dial__attack', ['datk_pos11'], unique=False)
    op.create_index(op.f('ix_dial__attack_datk_pos12'), 'dial__attack', ['datk_pos12'], unique=False)
    op.create_index(op.f('ix_dial__attack_datk_pos2'), 'dial__attack', ['datk_pos2'], unique=False)
    op.create_index(op.f('ix_dial__attack_datk_pos3'), 'dial__attack', ['datk_pos3'], unique=False)
    op.create_index(op.f('ix_dial__attack_datk_pos4'), 'dial__attack', ['datk_pos4'], unique=False)
    op.create_index(op.f('ix_dial__attack_datk_pos5'), 'dial__attack', ['datk_pos5'], unique=False)
    op.create_index(op.f('ix_dial__attack_datk_pos6'), 'dial__attack', ['datk_pos6'], unique=False)
    op.create_index(op.f('ix_dial__attack_datk_pos7'), 'dial__attack', ['datk_pos7'], unique=False)
    op.create_index(op.f('ix_dial__attack_datk_pos8'), 'dial__attack', ['datk_pos8'], unique=False)
    op.create_index(op.f('ix_dial__attack_datk_pos9'), 'dial__attack', ['datk_pos9'], unique=False)
    op.create_table('dial__damage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ddam_pos1', sa.String(length=2), nullable=True),
    sa.Column('ddam_pos2', sa.String(length=2), nullable=True),
    sa.Column('ddam_pos3', sa.String(length=2), nullable=True),
    sa.Column('ddam_pos4', sa.String(length=2), nullable=True),
    sa.Column('ddam_pos5', sa.String(length=2), nullable=True),
    sa.Column('ddam_pos6', sa.String(length=2), nullable=True),
    sa.Column('ddam_pos7', sa.String(length=2), nullable=True),
    sa.Column('ddam_pos8', sa.String(length=2), nullable=True),
    sa.Column('ddam_pos9', sa.String(length=2), nullable=True),
    sa.Column('ddam_pos10', sa.String(length=2), nullable=True),
    sa.Column('ddam_pos11', sa.String(length=2), nullable=True),
    sa.Column('ddam_pos12', sa.String(length=2), nullable=True),
    sa.Column('ddam_cor1', sa.String(length=30), nullable=True),
    sa.Column('ddam_cor2', sa.String(length=30), nullable=True),
    sa.Column('ddam_cor3', sa.String(length=30), nullable=True),
    sa.Column('ddam_cor4', sa.String(length=30), nullable=True),
    sa.Column('ddam_cor5', sa.String(length=30), nullable=True),
    sa.Column('ddam_cor6', sa.String(length=30), nullable=True),
    sa.Column('ddam_cor7', sa.String(length=30), nullable=True),
    sa.Column('ddam_cor8', sa.String(length=30), nullable=True),
    sa.Column('ddam_cor9', sa.String(length=30), nullable=True),
    sa.Column('ddam_cor10', sa.String(length=30), nullable=True),
    sa.Column('ddam_cor11', sa.String(length=30), nullable=True),
    sa.Column('ddam_cor12', sa.String(length=30), nullable=True),
    sa.Column('pieces_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pieces_id'], ['pieces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dial__damage_ddam_cor1'), 'dial__damage', ['ddam_cor1'], unique=False)
    op.create_index(op.f('ix_dial__damage_ddam_cor10'), 'dial__damage', ['ddam_cor10'], unique=False)
    op.create_index(op.f('ix_dial__damage_ddam_cor11'), 'dial__damage', ['ddam_cor11'], unique=False)
    op.create_index(op.f('ix_dial__damage_ddam_cor12'), 'dial__damage', ['ddam_cor12'], unique=False)
    op.create_index(op.f('ix_dial__damage_ddam_cor2'), 'dial__damage', ['ddam_cor2'], unique=False)
    op.create_index(op.f('ix_dial__damage_ddam_cor3'), 'dial__damage', ['ddam_cor3'], unique=False)
    op.create_index(op.f('ix_dial__damage_ddam_cor4'), 'dial__damage', ['ddam_cor4'], unique=False)
    op.create_index(op.f('ix_dial__damage_ddam_cor5'), 'dial__damage', ['ddam_cor5'], unique=False)
    op.create_index(op.f('ix_dial__damage_ddam_cor6'), 'dial__damage', ['ddam_cor6'], unique=False)
    op.create_index(op.f('ix_dial__damage_ddam_cor7'), 'dial__damage', ['ddam_cor7'], unique=False)
    op.create_index(op.f('ix_dial__damage_ddam_cor8'), 'dial__damage', ['ddam_cor8'], unique=False)
    op.create_index(op.f('ix_dial__damage_ddam_cor9'), 'dial__damage', ['ddam_cor9'], unique=False)
    op.create_index(op.f('ix_dial__damage_ddam_pos1'), 'dial__damage', ['ddam_pos1'], unique=False)
    op.create_index(op.f('ix_dial__damage_ddam_pos10'), 'dial__damage', ['ddam_pos10'], unique=False)
    op.create_index(op.f('ix_dial__damage_ddam_pos11'), 'dial__damage', ['ddam_pos11'], unique=False)
    op.create_index(op.f('ix_dial__damage_ddam_pos12'), 'dial__damage', ['ddam_pos12'], unique=False)
    op.create_index(op.f('ix_dial__damage_ddam_pos2'), 'dial__damage', ['ddam_pos2'], unique=False)
    op.create_index(op.f('ix_dial__damage_ddam_pos3'), 'dial__damage', ['ddam_pos3'], unique=False)
    op.create_index(op.f('ix_dial__damage_ddam_pos4'), 'dial__damage', ['ddam_pos4'], unique=False)
    op.create_index(op.f('ix_dial__damage_ddam_pos5'), 'dial__damage', ['ddam_pos5'], unique=False)
    op.create_index(op.f('ix_dial__damage_ddam_pos6'), 'dial__damage', ['ddam_pos6'], unique=False)
    op.create_index(op.f('ix_dial__damage_ddam_pos7'), 'dial__damage', ['ddam_pos7'], unique=False)
    op.create_index(op.f('ix_dial__damage_ddam_pos8'), 'dial__damage', ['ddam_pos8'], unique=False)
    op.create_index(op.f('ix_dial__damage_ddam_pos9'), 'dial__damage', ['ddam_pos9'], unique=False)
    op.create_table('dial__defense',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ddef_pos1', sa.String(length=2), nullable=True),
    sa.Column('ddef_pos2', sa.String(length=2), nullable=True),
    sa.Column('ddef_pos3', sa.String(length=2), nullable=True),
    sa.Column('ddef_pos4', sa.String(length=2), nullable=True),
    sa.Column('ddef_pos5', sa.String(length=2), nullable=True),
    sa.Column('ddef_pos6', sa.String(length=2), nullable=True),
    sa.Column('ddef_pos7', sa.String(length=2), nullable=True),
    sa.Column('ddef_pos8', sa.String(length=2), nullable=True),
    sa.Column('ddef_pos9', sa.String(length=2), nullable=True),
    sa.Column('ddef_pos10', sa.String(length=2), nullable=True),
    sa.Column('ddef_pos11', sa.String(length=2), nullable=True),
    sa.Column('ddef_pos12', sa.String(length=2), nullable=True),
    sa.Column('ddef_cor1', sa.String(length=30), nullable=True),
    sa.Column('ddef_cor2', sa.String(length=30), nullable=True),
    sa.Column('ddef_cor3', sa.String(length=30), nullable=True),
    sa.Column('ddef_cor4', sa.String(length=30), nullable=True),
    sa.Column('ddef_cor5', sa.String(length=30), nullable=True),
    sa.Column('ddef_cor6', sa.String(length=30), nullable=True),
    sa.Column('ddef_cor7', sa.String(length=30), nullable=True),
    sa.Column('ddef_cor8', sa.String(length=30), nullable=True),
    sa.Column('ddef_cor9', sa.String(length=30), nullable=True),
    sa.Column('ddef_cor10', sa.String(length=30), nullable=True),
    sa.Column('ddef_cor11', sa.String(length=30), nullable=True),
    sa.Column('ddef_cor12', sa.String(length=30), nullable=True),
    sa.Column('pieces_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pieces_id'], ['pieces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dial__defense_ddef_cor1'), 'dial__defense', ['ddef_cor1'], unique=False)
    op.create_index(op.f('ix_dial__defense_ddef_cor10'), 'dial__defense', ['ddef_cor10'], unique=False)
    op.create_index(op.f('ix_dial__defense_ddef_cor11'), 'dial__defense', ['ddef_cor11'], unique=False)
    op.create_index(op.f('ix_dial__defense_ddef_cor12'), 'dial__defense', ['ddef_cor12'], unique=False)
    op.create_index(op.f('ix_dial__defense_ddef_cor2'), 'dial__defense', ['ddef_cor2'], unique=False)
    op.create_index(op.f('ix_dial__defense_ddef_cor3'), 'dial__defense', ['ddef_cor3'], unique=False)
    op.create_index(op.f('ix_dial__defense_ddef_cor4'), 'dial__defense', ['ddef_cor4'], unique=False)
    op.create_index(op.f('ix_dial__defense_ddef_cor5'), 'dial__defense', ['ddef_cor5'], unique=False)
    op.create_index(op.f('ix_dial__defense_ddef_cor6'), 'dial__defense', ['ddef_cor6'], unique=False)
    op.create_index(op.f('ix_dial__defense_ddef_cor7'), 'dial__defense', ['ddef_cor7'], unique=False)
    op.create_index(op.f('ix_dial__defense_ddef_cor8'), 'dial__defense', ['ddef_cor8'], unique=False)
    op.create_index(op.f('ix_dial__defense_ddef_cor9'), 'dial__defense', ['ddef_cor9'], unique=False)
    op.create_index(op.f('ix_dial__defense_ddef_pos1'), 'dial__defense', ['ddef_pos1'], unique=False)
    op.create_index(op.f('ix_dial__defense_ddef_pos10'), 'dial__defense', ['ddef_pos10'], unique=False)
    op.create_index(op.f('ix_dial__defense_ddef_pos11'), 'dial__defense', ['ddef_pos11'], unique=False)
    op.create_index(op.f('ix_dial__defense_ddef_pos12'), 'dial__defense', ['ddef_pos12'], unique=False)
    op.create_index(op.f('ix_dial__defense_ddef_pos2'), 'dial__defense', ['ddef_pos2'], unique=False)
    op.create_index(op.f('ix_dial__defense_ddef_pos3'), 'dial__defense', ['ddef_pos3'], unique=False)
    op.create_index(op.f('ix_dial__defense_ddef_pos4'), 'dial__defense', ['ddef_pos4'], unique=False)
    op.create_index(op.f('ix_dial__defense_ddef_pos5'), 'dial__defense', ['ddef_pos5'], unique=False)
    op.create_index(op.f('ix_dial__defense_ddef_pos6'), 'dial__defense', ['ddef_pos6'], unique=False)
    op.create_index(op.f('ix_dial__defense_ddef_pos7'), 'dial__defense', ['ddef_pos7'], unique=False)
    op.create_index(op.f('ix_dial__defense_ddef_pos8'), 'dial__defense', ['ddef_pos8'], unique=False)
    op.create_index(op.f('ix_dial__defense_ddef_pos9'), 'dial__defense', ['ddef_pos9'], unique=False)
    op.create_table('dial__movement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dmov_pos1', sa.String(length=2), nullable=True),
    sa.Column('dmov_pos2', sa.String(length=2), nullable=True),
    sa.Column('dmov_pos3', sa.String(length=2), nullable=True),
    sa.Column('dmov_pos4', sa.String(length=2), nullable=True),
    sa.Column('dmov_pos5', sa.String(length=2), nullable=True),
    sa.Column('dmov_pos6', sa.String(length=2), nullable=True),
    sa.Column('dmov_pos7', sa.String(length=2), nullable=True),
    sa.Column('dmov_pos8', sa.String(length=2), nullable=True),
    sa.Column('dmov_pos9', sa.String(length=2), nullable=True),
    sa.Column('dmov_pos10', sa.String(length=2), nullable=True),
    sa.Column('dmov_pos11', sa.String(length=2), nullable=True),
    sa.Column('dmov_pos12', sa.String(length=2), nullable=True),
    sa.Column('dmov_cor1', sa.String(length=30), nullable=True),
    sa.Column('dmov_cor2', sa.String(length=30), nullable=True),
    sa.Column('dmov_cor3', sa.String(length=30), nullable=True),
    sa.Column('dmov_cor4', sa.String(length=30), nullable=True),
    sa.Column('dmov_cor5', sa.String(length=30), nullable=True),
    sa.Column('dmov_cor6', sa.String(length=30), nullable=True),
    sa.Column('dmov_cor7', sa.String(length=30), nullable=True),
    sa.Column('dmov_cor8', sa.String(length=30), nullable=True),
    sa.Column('dmov_cor9', sa.String(length=30), nullable=True),
    sa.Column('dmov_cor10', sa.String(length=30), nullable=True),
    sa.Column('dmov_cor11', sa.String(length=30), nullable=True),
    sa.Column('dmov_cor12', sa.String(length=30), nullable=True),
    sa.Column('pieces_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pieces_id'], ['pieces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dial__movement_dmov_cor1'), 'dial__movement', ['dmov_cor1'], unique=False)
    op.create_index(op.f('ix_dial__movement_dmov_cor10'), 'dial__movement', ['dmov_cor10'], unique=False)
    op.create_index(op.f('ix_dial__movement_dmov_cor11'), 'dial__movement', ['dmov_cor11'], unique=False)
    op.create_index(op.f('ix_dial__movement_dmov_cor12'), 'dial__movement', ['dmov_cor12'], unique=False)
    op.create_index(op.f('ix_dial__movement_dmov_cor2'), 'dial__movement', ['dmov_cor2'], unique=False)
    op.create_index(op.f('ix_dial__movement_dmov_cor3'), 'dial__movement', ['dmov_cor3'], unique=False)
    op.create_index(op.f('ix_dial__movement_dmov_cor4'), 'dial__movement', ['dmov_cor4'], unique=False)
    op.create_index(op.f('ix_dial__movement_dmov_cor5'), 'dial__movement', ['dmov_cor5'], unique=False)
    op.create_index(op.f('ix_dial__movement_dmov_cor6'), 'dial__movement', ['dmov_cor6'], unique=False)
    op.create_index(op.f('ix_dial__movement_dmov_cor7'), 'dial__movement', ['dmov_cor7'], unique=False)
    op.create_index(op.f('ix_dial__movement_dmov_cor8'), 'dial__movement', ['dmov_cor8'], unique=False)
    op.create_index(op.f('ix_dial__movement_dmov_cor9'), 'dial__movement', ['dmov_cor9'], unique=False)
    op.create_index(op.f('ix_dial__movement_dmov_pos1'), 'dial__movement', ['dmov_pos1'], unique=False)
    op.create_index(op.f('ix_dial__movement_dmov_pos10'), 'dial__movement', ['dmov_pos10'], unique=False)
    op.create_index(op.f('ix_dial__movement_dmov_pos11'), 'dial__movement', ['dmov_pos11'], unique=False)
    op.create_index(op.f('ix_dial__movement_dmov_pos12'), 'dial__movement', ['dmov_pos12'], unique=False)
    op.create_index(op.f('ix_dial__movement_dmov_pos2'), 'dial__movement', ['dmov_pos2'], unique=False)
    op.create_index(op.f('ix_dial__movement_dmov_pos3'), 'dial__movement', ['dmov_pos3'], unique=False)
    op.create_index(op.f('ix_dial__movement_dmov_pos4'), 'dial__movement', ['dmov_pos4'], unique=False)
    op.create_index(op.f('ix_dial__movement_dmov_pos5'), 'dial__movement', ['dmov_pos5'], unique=False)
    op.create_index(op.f('ix_dial__movement_dmov_pos6'), 'dial__movement', ['dmov_pos6'], unique=False)
    op.create_index(op.f('ix_dial__movement_dmov_pos7'), 'dial__movement', ['dmov_pos7'], unique=False)
    op.create_index(op.f('ix_dial__movement_dmov_pos8'), 'dial__movement', ['dmov_pos8'], unique=False)
    op.create_index(op.f('ix_dial__movement_dmov_pos9'), 'dial__movement', ['dmov_pos9'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dial__movement_dmov_pos9'), table_name='dial__movement')
    op.drop_index(op.f('ix_dial__movement_dmov_pos8'), table_name='dial__movement')
    op.drop_index(op.f('ix_dial__movement_dmov_pos7'), table_name='dial__movement')
    op.drop_index(op.f('ix_dial__movement_dmov_pos6'), table_name='dial__movement')
    op.drop_index(op.f('ix_dial__movement_dmov_pos5'), table_name='dial__movement')
    op.drop_index(op.f('ix_dial__movement_dmov_pos4'), table_name='dial__movement')
    op.drop_index(op.f('ix_dial__movement_dmov_pos3'), table_name='dial__movement')
    op.drop_index(op.f('ix_dial__movement_dmov_pos2'), table_name='dial__movement')
    op.drop_index(op.f('ix_dial__movement_dmov_pos12'), table_name='dial__movement')
    op.drop_index(op.f('ix_dial__movement_dmov_pos11'), table_name='dial__movement')
    op.drop_index(op.f('ix_dial__movement_dmov_pos10'), table_name='dial__movement')
    op.drop_index(op.f('ix_dial__movement_dmov_pos1'), table_name='dial__movement')
    op.drop_index(op.f('ix_dial__movement_dmov_cor9'), table_name='dial__movement')
    op.drop_index(op.f('ix_dial__movement_dmov_cor8'), table_name='dial__movement')
    op.drop_index(op.f('ix_dial__movement_dmov_cor7'), table_name='dial__movement')
    op.drop_index(op.f('ix_dial__movement_dmov_cor6'), table_name='dial__movement')
    op.drop_index(op.f('ix_dial__movement_dmov_cor5'), table_name='dial__movement')
    op.drop_index(op.f('ix_dial__movement_dmov_cor4'), table_name='dial__movement')
    op.drop_index(op.f('ix_dial__movement_dmov_cor3'), table_name='dial__movement')
    op.drop_index(op.f('ix_dial__movement_dmov_cor2'), table_name='dial__movement')
    op.drop_index(op.f('ix_dial__movement_dmov_cor12'), table_name='dial__movement')
    op.drop_index(op.f('ix_dial__movement_dmov_cor11'), table_name='dial__movement')
    op.drop_index(op.f('ix_dial__movement_dmov_cor10'), table_name='dial__movement')
    op.drop_index(op.f('ix_dial__movement_dmov_cor1'), table_name='dial__movement')
    op.drop_table('dial__movement')
    op.drop_index(op.f('ix_dial__defense_ddef_pos9'), table_name='dial__defense')
    op.drop_index(op.f('ix_dial__defense_ddef_pos8'), table_name='dial__defense')
    op.drop_index(op.f('ix_dial__defense_ddef_pos7'), table_name='dial__defense')
    op.drop_index(op.f('ix_dial__defense_ddef_pos6'), table_name='dial__defense')
    op.drop_index(op.f('ix_dial__defense_ddef_pos5'), table_name='dial__defense')
    op.drop_index(op.f('ix_dial__defense_ddef_pos4'), table_name='dial__defense')
    op.drop_index(op.f('ix_dial__defense_ddef_pos3'), table_name='dial__defense')
    op.drop_index(op.f('ix_dial__defense_ddef_pos2'), table_name='dial__defense')
    op.drop_index(op.f('ix_dial__defense_ddef_pos12'), table_name='dial__defense')
    op.drop_index(op.f('ix_dial__defense_ddef_pos11'), table_name='dial__defense')
    op.drop_index(op.f('ix_dial__defense_ddef_pos10'), table_name='dial__defense')
    op.drop_index(op.f('ix_dial__defense_ddef_pos1'), table_name='dial__defense')
    op.drop_index(op.f('ix_dial__defense_ddef_cor9'), table_name='dial__defense')
    op.drop_index(op.f('ix_dial__defense_ddef_cor8'), table_name='dial__defense')
    op.drop_index(op.f('ix_dial__defense_ddef_cor7'), table_name='dial__defense')
    op.drop_index(op.f('ix_dial__defense_ddef_cor6'), table_name='dial__defense')
    op.drop_index(op.f('ix_dial__defense_ddef_cor5'), table_name='dial__defense')
    op.drop_index(op.f('ix_dial__defense_ddef_cor4'), table_name='dial__defense')
    op.drop_index(op.f('ix_dial__defense_ddef_cor3'), table_name='dial__defense')
    op.drop_index(op.f('ix_dial__defense_ddef_cor2'), table_name='dial__defense')
    op.drop_index(op.f('ix_dial__defense_ddef_cor12'), table_name='dial__defense')
    op.drop_index(op.f('ix_dial__defense_ddef_cor11'), table_name='dial__defense')
    op.drop_index(op.f('ix_dial__defense_ddef_cor10'), table_name='dial__defense')
    op.drop_index(op.f('ix_dial__defense_ddef_cor1'), table_name='dial__defense')
    op.drop_table('dial__defense')
    op.drop_index(op.f('ix_dial__damage_ddam_pos9'), table_name='dial__damage')
    op.drop_index(op.f('ix_dial__damage_ddam_pos8'), table_name='dial__damage')
    op.drop_index(op.f('ix_dial__damage_ddam_pos7'), table_name='dial__damage')
    op.drop_index(op.f('ix_dial__damage_ddam_pos6'), table_name='dial__damage')
    op.drop_index(op.f('ix_dial__damage_ddam_pos5'), table_name='dial__damage')
    op.drop_index(op.f('ix_dial__damage_ddam_pos4'), table_name='dial__damage')
    op.drop_index(op.f('ix_dial__damage_ddam_pos3'), table_name='dial__damage')
    op.drop_index(op.f('ix_dial__damage_ddam_pos2'), table_name='dial__damage')
    op.drop_index(op.f('ix_dial__damage_ddam_pos12'), table_name='dial__damage')
    op.drop_index(op.f('ix_dial__damage_ddam_pos11'), table_name='dial__damage')
    op.drop_index(op.f('ix_dial__damage_ddam_pos10'), table_name='dial__damage')
    op.drop_index(op.f('ix_dial__damage_ddam_pos1'), table_name='dial__damage')
    op.drop_index(op.f('ix_dial__damage_ddam_cor9'), table_name='dial__damage')
    op.drop_index(op.f('ix_dial__damage_ddam_cor8'), table_name='dial__damage')
    op.drop_index(op.f('ix_dial__damage_ddam_cor7'), table_name='dial__damage')
    op.drop_index(op.f('ix_dial__damage_ddam_cor6'), table_name='dial__damage')
    op.drop_index(op.f('ix_dial__damage_ddam_cor5'), table_name='dial__damage')
    op.drop_index(op.f('ix_dial__damage_ddam_cor4'), table_name='dial__damage')
    op.drop_index(op.f('ix_dial__damage_ddam_cor3'), table_name='dial__damage')
    op.drop_index(op.f('ix_dial__damage_ddam_cor2'), table_name='dial__damage')
    op.drop_index(op.f('ix_dial__damage_ddam_cor12'), table_name='dial__damage')
    op.drop_index(op.f('ix_dial__damage_ddam_cor11'), table_name='dial__damage')
    op.drop_index(op.f('ix_dial__damage_ddam_cor10'), table_name='dial__damage')
    op.drop_index(op.f('ix_dial__damage_ddam_cor1'), table_name='dial__damage')
    op.drop_table('dial__damage')
    op.drop_index(op.f('ix_dial__attack_datk_pos9'), table_name='dial__attack')
    op.drop_index(op.f('ix_dial__attack_datk_pos8'), table_name='dial__attack')
    op.drop_index(op.f('ix_dial__attack_datk_pos7'), table_name='dial__attack')
    op.drop_index(op.f('ix_dial__attack_datk_pos6'), table_name='dial__attack')
    op.drop_index(op.f('ix_dial__attack_datk_pos5'), table_name='dial__attack')
    op.drop_index(op.f('ix_dial__attack_datk_pos4'), table_name='dial__attack')
    op.drop_index(op.f('ix_dial__attack_datk_pos3'), table_name='dial__attack')
    op.drop_index(op.f('ix_dial__attack_datk_pos2'), table_name='dial__attack')
    op.drop_index(op.f('ix_dial__attack_datk_pos12'), table_name='dial__attack')
    op.drop_index(op.f('ix_dial__attack_datk_pos11'), table_name='dial__attack')
    op.drop_index(op.f('ix_dial__attack_datk_pos10'), table_name='dial__attack')
    op.drop_index(op.f('ix_dial__attack_datk_pos1'), table_name='dial__attack')
    op.drop_index(op.f('ix_dial__attack_datk_cor9'), table_name='dial__attack')
    op.drop_index(op.f('ix_dial__attack_datk_cor8'), table_name='dial__attack')
    op.drop_index(op.f('ix_dial__attack_datk_cor7'), table_name='dial__attack')
    op.drop_index(op.f('ix_dial__attack_datk_cor6'), table_name='dial__attack')
    op.drop_index(op.f('ix_dial__attack_datk_cor5'), table_name='dial__attack')
    op.drop_index(op.f('ix_dial__attack_datk_cor4'), table_name='dial__attack')
    op.drop_index(op.f('ix_dial__attack_datk_cor3'), table_name='dial__attack')
    op.drop_index(op.f('ix_dial__attack_datk_cor2'), table_name='dial__attack')
    op.drop_index(op.f('ix_dial__attack_datk_cor12'), table_name='dial__attack')
    op.drop_index(op.f('ix_dial__attack_datk_cor11'), table_name='dial__attack')
    op.drop_index(op.f('ix_dial__attack_datk_cor10'), table_name='dial__attack')
    op.drop_index(op.f('ix_dial__attack_datk_cor1'), table_name='dial__attack')
    op.drop_table('dial__attack')
    op.drop_index(op.f('ix_pieces_piece_trait'), table_name='pieces')
    op.drop_index(op.f('ix_pieces_piece_real_name'), table_name='pieces')
    op.drop_index(op.f('ix_pieces_piece_number'), table_name='pieces')
    op.drop_index(op.f('ix_pieces_piece_name'), table_name='pieces')
    op.drop_index(op.f('ix_pieces_piece_mov_type'), table_name='pieces')
    op.drop_index(op.f('ix_pieces_piece_improved_target'), table_name='pieces')
    op.drop_index(op.f('ix_pieces_piece_improved_mov'), table_name='pieces')
    op.drop_index(op.f('ix_pieces_piece_def_type'), table_name='pieces')
    op.drop_index(op.f('ix_pieces_piece_dam_type'), table_name='pieces')
    op.drop_index(op.f('ix_pieces_piece_atk_type'), table_name='pieces')
    op.drop_table('pieces')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_collection_colle_name'), table_name='collection')
    op.drop_index(op.f('ix_collection_colle_initials'), table_name='collection')
    op.drop_index(op.f('ix_collection_colle_age'), table_name='collection')
    op.drop_table('collection')
    # ### end Alembic commands ###
