"""tabelas novas

Revision ID: b6c5ddfd5211
Revises: 
Create Date: 2018-06-15 23:38:09.800937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6c5ddfd5211'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('colle_name', sa.String(length=64), nullable=True),
    sa.Column('colle_initials', sa.String(length=10), nullable=True),
    sa.Column('colle_age', sa.String(length=60), nullable=True),
    sa.Column('colle_releasedate', sa.String(length=10), nullable=True),
    sa.Column('colle_piecequantity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collection_colle_age'), 'collection', ['colle_age'], unique=False)
    op.create_index(op.f('ix_collection_colle_initials'), 'collection', ['colle_initials'], unique=False)
    op.create_index(op.f('ix_collection_colle_name'), 'collection', ['colle_name'], unique=False)
    op.create_table('keywords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key_name', sa.String(length=25), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_keywords_key_name'), 'keywords', ['key_name'], unique=False)
    op.create_table('traits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trait_name', sa.String(length=20), nullable=True),
    sa.Column('trait_description', sa.String(length=3000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_traits_trait_description'), 'traits', ['trait_description'], unique=False)
    op.create_index(op.f('ix_traits_trait_name'), 'traits', ['trait_name'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('pieces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('piece_name', sa.String(length=64), nullable=True),
    sa.Column('piece_real_name', sa.String(length=64), nullable=True),
    sa.Column('piece_number', sa.String(), nullable=True),
    sa.Column('piece_point', sa.Integer(), nullable=True),
    sa.Column('piece_rarity', sa.String(length=10), nullable=True),
    sa.Column('piece_improved_target', sa.String(length=50), nullable=True),
    sa.Column('piece_improved_mov', sa.String(length=50), nullable=True),
    sa.Column('piece_mov_type', sa.String(length=20), nullable=True),
    sa.Column('piece_atk_type', sa.String(length=20), nullable=True),
    sa.Column('piece_def_type', sa.String(length=20), nullable=True),
    sa.Column('piece_dam_type', sa.String(length=20), nullable=True),
    sa.Column('piece_range', sa.Integer(), nullable=True),
    sa.Column('piece_bolts', sa.Integer(), nullable=True),
    sa.Column('collection_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pieces_piece_atk_type'), 'pieces', ['piece_atk_type'], unique=False)
    op.create_index(op.f('ix_pieces_piece_dam_type'), 'pieces', ['piece_dam_type'], unique=False)
    op.create_index(op.f('ix_pieces_piece_def_type'), 'pieces', ['piece_def_type'], unique=False)
    op.create_index(op.f('ix_pieces_piece_improved_mov'), 'pieces', ['piece_improved_mov'], unique=False)
    op.create_index(op.f('ix_pieces_piece_improved_target'), 'pieces', ['piece_improved_target'], unique=False)
    op.create_index(op.f('ix_pieces_piece_mov_type'), 'pieces', ['piece_mov_type'], unique=False)
    op.create_index(op.f('ix_pieces_piece_name'), 'pieces', ['piece_name'], unique=False)
    op.create_index(op.f('ix_pieces_piece_number'), 'pieces', ['piece_number'], unique=False)
    op.create_index(op.f('ix_pieces_piece_point'), 'pieces', ['piece_point'], unique=False)
    op.create_index(op.f('ix_pieces_piece_rarity'), 'pieces', ['piece_rarity'], unique=False)
    op.create_index(op.f('ix_pieces_piece_real_name'), 'pieces', ['piece_real_name'], unique=False)
    op.create_table('dial__attack',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datk_pos1', sa.String(length=2), nullable=True),
    sa.Column('datk_pos2', sa.String(length=2), nullable=True),
    sa.Column('datk_pos3', sa.String(length=2), nullable=True),
    sa.Column('datk_pos4', sa.String(length=2), nullable=True),
    sa.Column('datk_pos5', sa.String(length=2), nullable=True),
    sa.Column('datk_pos6', sa.String(length=2), nullable=True),
    sa.Column('datk_pos7', sa.String(length=2), nullable=True),
    sa.Column('datk_pos8', sa.String(length=2), nullable=True),
    sa.Column('datk_pos9', sa.String(length=2), nullable=True),
    sa.Column('datk_pos10', sa.String(length=2), nullable=True),
    sa.Column('datk_pos11', sa.String(length=2), nullable=True),
    sa.Column('datk_pos12', sa.String(length=2), nullable=True),
    sa.Column('datk_pos13', sa.String(length=2), nullable=True),
    sa.Column('datk_pos14', sa.String(length=2), nullable=True),
    sa.Column('datk_pos15', sa.String(length=2), nullable=True),
    sa.Column('datk_pos16', sa.String(length=2), nullable=True),
    sa.Column('datk_pos17', sa.String(length=2), nullable=True),
    sa.Column('datk_pos18', sa.String(length=2), nullable=True),
    sa.Column('datk_pos19', sa.String(length=2), nullable=True),
    sa.Column('datk_pos20', sa.String(length=2), nullable=True),
    sa.Column('datk_pos21', sa.String(length=2), nullable=True),
    sa.Column('datk_pos22', sa.String(length=2), nullable=True),
    sa.Column('datk_pos23', sa.String(length=2), nullable=True),
    sa.Column('datk_pos24', sa.String(length=2), nullable=True),
    sa.Column('datk_pos25', sa.String(length=2), nullable=True),
    sa.Column('datk_pos26', sa.String(length=2), nullable=True),
    sa.Column('datk_cor1', sa.String(length=30), nullable=True),
    sa.Column('datk_cor2', sa.String(length=30), nullable=True),
    sa.Column('datk_cor3', sa.String(length=30), nullable=True),
    sa.Column('datk_cor4', sa.String(length=30), nullable=True),
    sa.Column('datk_cor5', sa.String(length=30), nullable=True),
    sa.Column('datk_cor6', sa.String(length=30), nullable=True),
    sa.Column('datk_cor7', sa.String(length=30), nullable=True),
    sa.Column('datk_cor8', sa.String(length=30), nullable=True),
    sa.Column('datk_cor9', sa.String(length=30), nullable=True),
    sa.Column('datk_cor10', sa.String(length=30), nullable=True),
    sa.Column('datk_cor11', sa.String(length=30), nullable=True),
    sa.Column('datk_cor12', sa.String(length=30), nullable=True),
    sa.Column('datk_cor13', sa.String(length=30), nullable=True),
    sa.Column('datk_cor14', sa.String(length=30), nullable=True),
    sa.Column('datk_cor15', sa.String(length=30), nullable=True),
    sa.Column('datk_cor16', sa.String(length=30), nullable=True),
    sa.Column('datk_cor17', sa.String(length=30), nullable=True),
    sa.Column('datk_cor18', sa.String(length=30), nullable=True),
    sa.Column('datk_cor19', sa.String(length=30), nullable=True),
    sa.Column('datk_cor20', sa.String(length=30), nullable=True),
    sa.Column('datk_cor21', sa.String(length=30), nullable=True),
    sa.Column('datk_cor22', sa.String(length=30), nullable=True),
    sa.Column('datk_cor23', sa.String(length=30), nullable=True),
    sa.Column('datk_cor24', sa.String(length=30), nullable=True),
    sa.Column('datk_cor25', sa.String(length=30), nullable=True),
    sa.Column('datk_cor26', sa.String(length=30), nullable=True),
    sa.Column('pieces_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pieces_id'], ['pieces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dial__attack_datk_cor1'), 'dial__attack', ['datk_cor1'], unique=False)
    op.create_index(op.f('ix_dial__attack_datk_cor10'), 'dial__attack', ['datk_cor10'], unique=False)
    op.create_index(op.f('ix_dial__attack_datk_cor11'), 'dial__attack', ['datk_cor11'], unique=False)
    op.create_index(op.f('ix_dial__attack_datk_cor12'), 'dial__attack', ['datk_cor12'], unique=False)
    op.create_index(op.f('ix_dial__attack_datk_cor13'), 'dial__attack', ['datk_cor13'], unique=False)
    op.create_index(op.f('ix_dial__attack_datk_cor14'), 'dial__attack', ['datk_cor14'], unique=False)
    op.create_index(op.f('ix_dial__attack_datk_cor15'), 'dial__attack', ['datk_cor15'], unique=False)
    op.create_index(op.f('ix_dial__attack_datk_cor16'), 'dial__attack', ['datk_cor16'], unique=False)
    op.create_index(op.f('ix_dial__attack_datk_cor17'), 'dial__attack', ['datk_cor17'], unique=False)
    op.create_index(op.f('ix_dial__attack_datk_cor18'), 'dial__attack', ['datk_cor18'], unique=False)
    op.create_index(op.f('ix_dial__attack_datk_cor19'), 'dial__attack', ['datk_cor19'], unique=False)
    op.create_index(op.f('ix_dial__attack_datk_cor2'), 'dial__attack', ['datk_cor2'], unique=False)
    op.create_index(op.f('ix_dial__attack_datk_cor20'), 'dial__attack', ['datk_cor20'], unique=False)
    op.create_index(op.f('ix_dial__attack_datk_cor21'), 'dial__attack', ['datk_cor21'], unique=False)
    op.create_index(op.f('ix_dial__attack_datk_cor22'), 'dial__attack', ['datk_cor22'], unique=False)
    op.create_index(op.f('ix_dial__attack_datk_cor23'), 'dial__attack', ['datk_cor23'], unique=False)
    op.create_index(op.f('ix_dial__attack_datk_cor24'), 'dial__attack', ['datk_cor24'], unique=False)
    op.create_index(op.f('ix_dial__attack_datk_cor25'), 'dial__attack', ['datk_cor25'], unique=False)
    op.create_index(op.f('ix_dial__attack_datk_cor26'), 'dial__attack', ['datk_cor26'], unique=False)
    op.create_index(op.f('ix_dial__attack_datk_cor3'), 'dial__attack', ['datk_cor3'], unique=False)
    op.create_index(op.f('ix_dial__attack_datk_cor4'), 'dial__attack', ['datk_cor4'], unique=False)
    op.create_index(op.f('ix_dial__attack_datk_cor5'), 'dial__attack', ['datk_cor5'], unique=False)
    op.create_index(op.f('ix_dial__attack_datk_cor6'), 'dial__attack', ['datk_cor6'], unique=False)
    op.create_index(op.f('ix_dial__attack_datk_cor7'), 'dial__attack', ['datk_cor7'], unique=False)
    op.create_index(op.f('ix_dial__attack_datk_cor8'), 'dial__attack', ['datk_cor8'], unique=False)
    op.create_index(op.f('ix_dial__attack_datk_cor9'), 'dial__attack', ['datk_cor9'], unique=False)
    op.create_index(op.f('ix_dial__attack_datk_pos1'), 'dial__attack', ['datk_pos1'], unique=False)
    op.create_index(op.f('ix_dial__attack_datk_pos10'), 'dial__attack', ['datk_pos10'], unique=False)
    op.create_index(op.f('ix_dial__attack_datk_pos11'), 'dial__attack', ['datk_pos11'], unique=False)
    op.create_index(op.f('ix_dial__attack_datk_pos12'), 'dial__attack', ['datk_pos12'], unique=False)
    op.create_index(op.f('ix_dial__attack_datk_pos13'), 'dial__attack', ['datk_pos13'], unique=False)
    op.create_index(op.f('ix_dial__attack_datk_pos14'), 'dial__attack', ['datk_pos14'], unique=False)
    op.create_index(op.f('ix_dial__attack_datk_pos15'), 'dial__attack', ['datk_pos15'], unique=False)
    op.create_index(op.f('ix_dial__attack_datk_pos16'), 'dial__attack', ['datk_pos16'], unique=False)
    op.create_index(op.f('ix_dial__attack_datk_pos17'), 'dial__attack', ['datk_pos17'], unique=False)
    op.create_index(op.f('ix_dial__attack_datk_pos18'), 'dial__attack', ['datk_pos18'], unique=False)
    op.create_index(op.f('ix_dial__attack_datk_pos19'), 'dial__attack', ['datk_pos19'], unique=False)
    op.create_index(op.f('ix_dial__attack_datk_pos2'), 'dial__attack', ['datk_pos2'], unique=False)
    op.create_index(op.f('ix_dial__attack_datk_pos20'), 'dial__attack', ['datk_pos20'], unique=False)
    op.create_index(op.f('ix_dial__attack_datk_pos21'), 'dial__attack', ['datk_pos21'], unique=False)
    op.create_index(op.f('ix_dial__attack_datk_pos22'), 'dial__attack', ['datk_pos22'], unique=False)
    op.create_index(op.f('ix_dial__attack_datk_pos23'), 'dial__attack', ['datk_pos23'], unique=False)
    op.create_index(op.f('ix_dial__attack_datk_pos24'), 'dial__attack', ['datk_pos24'], unique=False)
    op.create_index(op.f('ix_dial__attack_datk_pos25'), 'dial__attack', ['datk_pos25'], unique=False)
    op.create_index(op.f('ix_dial__attack_datk_pos26'), 'dial__attack', ['datk_pos26'], unique=False)
    op.create_index(op.f('ix_dial__attack_datk_pos3'), 'dial__attack', ['datk_pos3'], unique=False)
    op.create_index(op.f('ix_dial__attack_datk_pos4'), 'dial__attack', ['datk_pos4'], unique=False)
    op.create_index(op.f('ix_dial__attack_datk_pos5'), 'dial__attack', ['datk_pos5'], unique=False)
    op.create_index(op.f('ix_dial__attack_datk_pos6'), 'dial__attack', ['datk_pos6'], unique=False)
    op.create_index(op.f('ix_dial__attack_datk_pos7'), 'dial__attack', ['datk_pos7'], unique=False)
    op.create_index(op.f('ix_dial__attack_datk_pos8'), 'dial__attack', ['datk_pos8'], unique=False)
    op.create_index(op.f('ix_dial__attack_datk_pos9'), 'dial__attack', ['datk_pos9'], unique=False)
    op.create_table('dial__damage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ddam_pos1', sa.String(length=2), nullable=True),
    sa.Column('ddam_pos2', sa.String(length=2), nullable=True),
    sa.Column('ddam_pos3', sa.String(length=2), nullable=True),
    sa.Column('ddam_pos4', sa.String(length=2), nullable=True),
    sa.Column('ddam_pos5', sa.String(length=2), nullable=True),
    sa.Column('ddam_pos6', sa.String(length=2), nullable=True),
    sa.Column('ddam_pos7', sa.String(length=2), nullable=True),
    sa.Column('ddam_pos8', sa.String(length=2), nullable=True),
    sa.Column('ddam_pos9', sa.String(length=2), nullable=True),
    sa.Column('ddam_pos10', sa.String(length=2), nullable=True),
    sa.Column('ddam_pos11', sa.String(length=2), nullable=True),
    sa.Column('ddam_pos12', sa.String(length=2), nullable=True),
    sa.Column('ddam_pos13', sa.String(length=2), nullable=True),
    sa.Column('ddam_pos14', sa.String(length=2), nullable=True),
    sa.Column('ddam_pos15', sa.String(length=2), nullable=True),
    sa.Column('ddam_pos16', sa.String(length=2), nullable=True),
    sa.Column('ddam_pos17', sa.String(length=2), nullable=True),
    sa.Column('ddam_pos18', sa.String(length=2), nullable=True),
    sa.Column('ddam_pos19', sa.String(length=2), nullable=True),
    sa.Column('ddam_pos20', sa.String(length=2), nullable=True),
    sa.Column('ddam_pos21', sa.String(length=2), nullable=True),
    sa.Column('ddam_pos22', sa.String(length=2), nullable=True),
    sa.Column('ddam_pos23', sa.String(length=2), nullable=True),
    sa.Column('ddam_pos24', sa.String(length=2), nullable=True),
    sa.Column('ddam_pos25', sa.String(length=2), nullable=True),
    sa.Column('ddam_pos26', sa.String(length=2), nullable=True),
    sa.Column('ddam_cor1', sa.String(length=30), nullable=True),
    sa.Column('ddam_cor2', sa.String(length=30), nullable=True),
    sa.Column('ddam_cor3', sa.String(length=30), nullable=True),
    sa.Column('ddam_cor4', sa.String(length=30), nullable=True),
    sa.Column('ddam_cor5', sa.String(length=30), nullable=True),
    sa.Column('ddam_cor6', sa.String(length=30), nullable=True),
    sa.Column('ddam_cor7', sa.String(length=30), nullable=True),
    sa.Column('ddam_cor8', sa.String(length=30), nullable=True),
    sa.Column('ddam_cor9', sa.String(length=30), nullable=True),
    sa.Column('ddam_cor10', sa.String(length=30), nullable=True),
    sa.Column('ddam_cor11', sa.String(length=30), nullable=True),
    sa.Column('ddam_cor12', sa.String(length=30), nullable=True),
    sa.Column('ddam_cor13', sa.String(length=30), nullable=True),
    sa.Column('ddam_cor14', sa.String(length=30), nullable=True),
    sa.Column('ddam_cor15', sa.String(length=30), nullable=True),
    sa.Column('ddam_cor16', sa.String(length=30), nullable=True),
    sa.Column('ddam_cor17', sa.String(length=30), nullable=True),
    sa.Column('ddam_cor18', sa.String(length=30), nullable=True),
    sa.Column('ddam_cor19', sa.String(length=30), nullable=True),
    sa.Column('ddam_cor20', sa.String(length=30), nullable=True),
    sa.Column('ddam_cor21', sa.String(length=30), nullable=True),
    sa.Column('ddam_cor22', sa.String(length=30), nullable=True),
    sa.Column('ddam_cor23', sa.String(length=30), nullable=True),
    sa.Column('ddam_cor24', sa.String(length=30), nullable=True),
    sa.Column('ddam_cor25', sa.String(length=30), nullable=True),
    sa.Column('ddam_cor26', sa.String(length=30), nullable=True),
    sa.Column('pieces_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pieces_id'], ['pieces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dial__damage_ddam_cor1'), 'dial__damage', ['ddam_cor1'], unique=False)
    op.create_index(op.f('ix_dial__damage_ddam_cor10'), 'dial__damage', ['ddam_cor10'], unique=False)
    op.create_index(op.f('ix_dial__damage_ddam_cor11'), 'dial__damage', ['ddam_cor11'], unique=False)
    op.create_index(op.f('ix_dial__damage_ddam_cor12'), 'dial__damage', ['ddam_cor12'], unique=False)
    op.create_index(op.f('ix_dial__damage_ddam_cor13'), 'dial__damage', ['ddam_cor13'], unique=False)
    op.create_index(op.f('ix_dial__damage_ddam_cor14'), 'dial__damage', ['ddam_cor14'], unique=False)
    op.create_index(op.f('ix_dial__damage_ddam_cor15'), 'dial__damage', ['ddam_cor15'], unique=False)
    op.create_index(op.f('ix_dial__damage_ddam_cor16'), 'dial__damage', ['ddam_cor16'], unique=False)
    op.create_index(op.f('ix_dial__damage_ddam_cor17'), 'dial__damage', ['ddam_cor17'], unique=False)
    op.create_index(op.f('ix_dial__damage_ddam_cor18'), 'dial__damage', ['ddam_cor18'], unique=False)
    op.create_index(op.f('ix_dial__damage_ddam_cor19'), 'dial__damage', ['ddam_cor19'], unique=False)
    op.create_index(op.f('ix_dial__damage_ddam_cor2'), 'dial__damage', ['ddam_cor2'], unique=False)
    op.create_index(op.f('ix_dial__damage_ddam_cor20'), 'dial__damage', ['ddam_cor20'], unique=False)
    op.create_index(op.f('ix_dial__damage_ddam_cor21'), 'dial__damage', ['ddam_cor21'], unique=False)
    op.create_index(op.f('ix_dial__damage_ddam_cor22'), 'dial__damage', ['ddam_cor22'], unique=False)
    op.create_index(op.f('ix_dial__damage_ddam_cor23'), 'dial__damage', ['ddam_cor23'], unique=False)
    op.create_index(op.f('ix_dial__damage_ddam_cor24'), 'dial__damage', ['ddam_cor24'], unique=False)
    op.create_index(op.f('ix_dial__damage_ddam_cor25'), 'dial__damage', ['ddam_cor25'], unique=False)
    op.create_index(op.f('ix_dial__damage_ddam_cor26'), 'dial__damage', ['ddam_cor26'], unique=False)
    op.create_index(op.f('ix_dial__damage_ddam_cor3'), 'dial__damage', ['ddam_cor3'], unique=False)
    op.create_index(op.f('ix_dial__damage_ddam_cor4'), 'dial__damage', ['ddam_cor4'], unique=False)
    op.create_index(op.f('ix_dial__damage_ddam_cor5'), 'dial__damage', ['ddam_cor5'], unique=False)
    op.create_index(op.f('ix_dial__damage_ddam_cor6'), 'dial__damage', ['ddam_cor6'], unique=False)
    op.create_index(op.f('ix_dial__damage_ddam_cor7'), 'dial__damage', ['ddam_cor7'], unique=False)
    op.create_index(op.f('ix_dial__damage_ddam_cor8'), 'dial__damage', ['ddam_cor8'], unique=False)
    op.create_index(op.f('ix_dial__damage_ddam_cor9'), 'dial__damage', ['ddam_cor9'], unique=False)
    op.create_index(op.f('ix_dial__damage_ddam_pos1'), 'dial__damage', ['ddam_pos1'], unique=False)
    op.create_index(op.f('ix_dial__damage_ddam_pos10'), 'dial__damage', ['ddam_pos10'], unique=False)
    op.create_index(op.f('ix_dial__damage_ddam_pos11'), 'dial__damage', ['ddam_pos11'], unique=False)
    op.create_index(op.f('ix_dial__damage_ddam_pos12'), 'dial__damage', ['ddam_pos12'], unique=False)
    op.create_index(op.f('ix_dial__damage_ddam_pos13'), 'dial__damage', ['ddam_pos13'], unique=False)
    op.create_index(op.f('ix_dial__damage_ddam_pos14'), 'dial__damage', ['ddam_pos14'], unique=False)
    op.create_index(op.f('ix_dial__damage_ddam_pos15'), 'dial__damage', ['ddam_pos15'], unique=False)
    op.create_index(op.f('ix_dial__damage_ddam_pos16'), 'dial__damage', ['ddam_pos16'], unique=False)
    op.create_index(op.f('ix_dial__damage_ddam_pos17'), 'dial__damage', ['ddam_pos17'], unique=False)
    op.create_index(op.f('ix_dial__damage_ddam_pos18'), 'dial__damage', ['ddam_pos18'], unique=False)
    op.create_index(op.f('ix_dial__damage_ddam_pos19'), 'dial__damage', ['ddam_pos19'], unique=False)
    op.create_index(op.f('ix_dial__damage_ddam_pos2'), 'dial__damage', ['ddam_pos2'], unique=False)
    op.create_index(op.f('ix_dial__damage_ddam_pos20'), 'dial__damage', ['ddam_pos20'], unique=False)
    op.create_index(op.f('ix_dial__damage_ddam_pos21'), 'dial__damage', ['ddam_pos21'], unique=False)
    op.create_index(op.f('ix_dial__damage_ddam_pos22'), 'dial__damage', ['ddam_pos22'], unique=False)
    op.create_index(op.f('ix_dial__damage_ddam_pos23'), 'dial__damage', ['ddam_pos23'], unique=False)
    op.create_index(op.f('ix_dial__damage_ddam_pos24'), 'dial__damage', ['ddam_pos24'], unique=False)
    op.create_index(op.f('ix_dial__damage_ddam_pos25'), 'dial__damage', ['ddam_pos25'], unique=False)
    op.create_index(op.f('ix_dial__damage_ddam_pos26'), 'dial__damage', ['ddam_pos26'], unique=False)
    op.create_index(op.f('ix_dial__damage_ddam_pos3'), 'dial__damage', ['ddam_pos3'], unique=False)
    op.create_index(op.f('ix_dial__damage_ddam_pos4'), 'dial__damage', ['ddam_pos4'], unique=False)
    op.create_index(op.f('ix_dial__damage_ddam_pos5'), 'dial__damage', ['ddam_pos5'], unique=False)
    op.create_index(op.f('ix_dial__damage_ddam_pos6'), 'dial__damage', ['ddam_pos6'], unique=False)
    op.create_index(op.f('ix_dial__damage_ddam_pos7'), 'dial__damage', ['ddam_pos7'], unique=False)
    op.create_index(op.f('ix_dial__damage_ddam_pos8'), 'dial__damage', ['ddam_pos8'], unique=False)
    op.create_index(op.f('ix_dial__damage_ddam_pos9'), 'dial__damage', ['ddam_pos9'], unique=False)
    op.create_table('dial__defense',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ddef_pos1', sa.String(length=2), nullable=True),
    sa.Column('ddef_pos2', sa.String(length=2), nullable=True),
    sa.Column('ddef_pos3', sa.String(length=2), nullable=True),
    sa.Column('ddef_pos4', sa.String(length=2), nullable=True),
    sa.Column('ddef_pos5', sa.String(length=2), nullable=True),
    sa.Column('ddef_pos6', sa.String(length=2), nullable=True),
    sa.Column('ddef_pos7', sa.String(length=2), nullable=True),
    sa.Column('ddef_pos8', sa.String(length=2), nullable=True),
    sa.Column('ddef_pos9', sa.String(length=2), nullable=True),
    sa.Column('ddef_pos10', sa.String(length=2), nullable=True),
    sa.Column('ddef_pos11', sa.String(length=2), nullable=True),
    sa.Column('ddef_pos12', sa.String(length=2), nullable=True),
    sa.Column('ddef_pos13', sa.String(length=2), nullable=True),
    sa.Column('ddef_pos14', sa.String(length=2), nullable=True),
    sa.Column('ddef_pos15', sa.String(length=2), nullable=True),
    sa.Column('ddef_pos16', sa.String(length=2), nullable=True),
    sa.Column('ddef_pos17', sa.String(length=2), nullable=True),
    sa.Column('ddef_pos18', sa.String(length=2), nullable=True),
    sa.Column('ddef_pos19', sa.String(length=2), nullable=True),
    sa.Column('ddef_pos20', sa.String(length=2), nullable=True),
    sa.Column('ddef_pos21', sa.String(length=2), nullable=True),
    sa.Column('ddef_pos22', sa.String(length=2), nullable=True),
    sa.Column('ddef_pos23', sa.String(length=2), nullable=True),
    sa.Column('ddef_pos24', sa.String(length=2), nullable=True),
    sa.Column('ddef_pos25', sa.String(length=2), nullable=True),
    sa.Column('ddef_pos26', sa.String(length=2), nullable=True),
    sa.Column('ddef_cor1', sa.String(length=30), nullable=True),
    sa.Column('ddef_cor2', sa.String(length=30), nullable=True),
    sa.Column('ddef_cor3', sa.String(length=30), nullable=True),
    sa.Column('ddef_cor4', sa.String(length=30), nullable=True),
    sa.Column('ddef_cor5', sa.String(length=30), nullable=True),
    sa.Column('ddef_cor6', sa.String(length=30), nullable=True),
    sa.Column('ddef_cor7', sa.String(length=30), nullable=True),
    sa.Column('ddef_cor8', sa.String(length=30), nullable=True),
    sa.Column('ddef_cor9', sa.String(length=30), nullable=True),
    sa.Column('ddef_cor10', sa.String(length=30), nullable=True),
    sa.Column('ddef_cor11', sa.String(length=30), nullable=True),
    sa.Column('ddef_cor12', sa.String(length=30), nullable=True),
    sa.Column('ddef_cor13', sa.String(length=30), nullable=True),
    sa.Column('ddef_cor14', sa.String(length=30), nullable=True),
    sa.Column('ddef_cor15', sa.String(length=30), nullable=True),
    sa.Column('ddef_cor16', sa.String(length=30), nullable=True),
    sa.Column('ddef_cor17', sa.String(length=30), nullable=True),
    sa.Column('ddef_cor18', sa.String(length=30), nullable=True),
    sa.Column('ddef_cor19', sa.String(length=30), nullable=True),
    sa.Column('ddef_cor20', sa.String(length=30), nullable=True),
    sa.Column('ddef_cor21', sa.String(length=30), nullable=True),
    sa.Column('ddef_cor22', sa.String(length=30), nullable=True),
    sa.Column('ddef_cor23', sa.String(length=30), nullable=True),
    sa.Column('ddef_cor24', sa.String(length=30), nullable=True),
    sa.Column('ddef_cor25', sa.String(length=30), nullable=True),
    sa.Column('ddef_cor26', sa.String(length=30), nullable=True),
    sa.Column('pieces_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pieces_id'], ['pieces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dial__defense_ddef_cor1'), 'dial__defense', ['ddef_cor1'], unique=False)
    op.create_index(op.f('ix_dial__defense_ddef_cor10'), 'dial__defense', ['ddef_cor10'], unique=False)
    op.create_index(op.f('ix_dial__defense_ddef_cor11'), 'dial__defense', ['ddef_cor11'], unique=False)
    op.create_index(op.f('ix_dial__defense_ddef_cor12'), 'dial__defense', ['ddef_cor12'], unique=False)
    op.create_index(op.f('ix_dial__defense_ddef_cor13'), 'dial__defense', ['ddef_cor13'], unique=False)
    op.create_index(op.f('ix_dial__defense_ddef_cor14'), 'dial__defense', ['ddef_cor14'], unique=False)
    op.create_index(op.f('ix_dial__defense_ddef_cor15'), 'dial__defense', ['ddef_cor15'], unique=False)
    op.create_index(op.f('ix_dial__defense_ddef_cor16'), 'dial__defense', ['ddef_cor16'], unique=False)
    op.create_index(op.f('ix_dial__defense_ddef_cor17'), 'dial__defense', ['ddef_cor17'], unique=False)
    op.create_index(op.f('ix_dial__defense_ddef_cor18'), 'dial__defense', ['ddef_cor18'], unique=False)
    op.create_index(op.f('ix_dial__defense_ddef_cor19'), 'dial__defense', ['ddef_cor19'], unique=False)
    op.create_index(op.f('ix_dial__defense_ddef_cor2'), 'dial__defense', ['ddef_cor2'], unique=False)
    op.create_index(op.f('ix_dial__defense_ddef_cor20'), 'dial__defense', ['ddef_cor20'], unique=False)
    op.create_index(op.f('ix_dial__defense_ddef_cor21'), 'dial__defense', ['ddef_cor21'], unique=False)
    op.create_index(op.f('ix_dial__defense_ddef_cor22'), 'dial__defense', ['ddef_cor22'], unique=False)
    op.create_index(op.f('ix_dial__defense_ddef_cor23'), 'dial__defense', ['ddef_cor23'], unique=False)
    op.create_index(op.f('ix_dial__defense_ddef_cor24'), 'dial__defense', ['ddef_cor24'], unique=False)
    op.create_index(op.f('ix_dial__defense_ddef_cor25'), 'dial__defense', ['ddef_cor25'], unique=False)
    op.create_index(op.f('ix_dial__defense_ddef_cor26'), 'dial__defense', ['ddef_cor26'], unique=False)
    op.create_index(op.f('ix_dial__defense_ddef_cor3'), 'dial__defense', ['ddef_cor3'], unique=False)
    op.create_index(op.f('ix_dial__defense_ddef_cor4'), 'dial__defense', ['ddef_cor4'], unique=False)
    op.create_index(op.f('ix_dial__defense_ddef_cor5'), 'dial__defense', ['ddef_cor5'], unique=False)
    op.create_index(op.f('ix_dial__defense_ddef_cor6'), 'dial__defense', ['ddef_cor6'], unique=False)
    op.create_index(op.f('ix_dial__defense_ddef_cor7'), 'dial__defense', ['ddef_cor7'], unique=False)
    op.create_index(op.f('ix_dial__defense_ddef_cor8'), 'dial__defense', ['ddef_cor8'], unique=False)
    op.create_index(op.f('ix_dial__defense_ddef_cor9'), 'dial__defense', ['ddef_cor9'], unique=False)
    op.create_index(op.f('ix_dial__defense_ddef_pos1'), 'dial__defense', ['ddef_pos1'], unique=False)
    op.create_index(op.f('ix_dial__defense_ddef_pos10'), 'dial__defense', ['ddef_pos10'], unique=False)
    op.create_index(op.f('ix_dial__defense_ddef_pos11'), 'dial__defense', ['ddef_pos11'], unique=False)
    op.create_index(op.f('ix_dial__defense_ddef_pos12'), 'dial__defense', ['ddef_pos12'], unique=False)
    op.create_index(op.f('ix_dial__defense_ddef_pos13'), 'dial__defense', ['ddef_pos13'], unique=False)
    op.create_index(op.f('ix_dial__defense_ddef_pos14'), 'dial__defense', ['ddef_pos14'], unique=False)
    op.create_index(op.f('ix_dial__defense_ddef_pos15'), 'dial__defense', ['ddef_pos15'], unique=False)
    op.create_index(op.f('ix_dial__defense_ddef_pos16'), 'dial__defense', ['ddef_pos16'], unique=False)
    op.create_index(op.f('ix_dial__defense_ddef_pos17'), 'dial__defense', ['ddef_pos17'], unique=False)
    op.create_index(op.f('ix_dial__defense_ddef_pos18'), 'dial__defense', ['ddef_pos18'], unique=False)
    op.create_index(op.f('ix_dial__defense_ddef_pos19'), 'dial__defense', ['ddef_pos19'], unique=False)
    op.create_index(op.f('ix_dial__defense_ddef_pos2'), 'dial__defense', ['ddef_pos2'], unique=False)
    op.create_index(op.f('ix_dial__defense_ddef_pos20'), 'dial__defense', ['ddef_pos20'], unique=False)
    op.create_index(op.f('ix_dial__defense_ddef_pos21'), 'dial__defense', ['ddef_pos21'], unique=False)
    op.create_index(op.f('ix_dial__defense_ddef_pos22'), 'dial__defense', ['ddef_pos22'], unique=False)
    op.create_index(op.f('ix_dial__defense_ddef_pos23'), 'dial__defense', ['ddef_pos23'], unique=False)
    op.create_index(op.f('ix_dial__defense_ddef_pos24'), 'dial__defense', ['ddef_pos24'], unique=False)
    op.create_index(op.f('ix_dial__defense_ddef_pos25'), 'dial__defense', ['ddef_pos25'], unique=False)
    op.create_index(op.f('ix_dial__defense_ddef_pos26'), 'dial__defense', ['ddef_pos26'], unique=False)
    op.create_index(op.f('ix_dial__defense_ddef_pos3'), 'dial__defense', ['ddef_pos3'], unique=False)
    op.create_index(op.f('ix_dial__defense_ddef_pos4'), 'dial__defense', ['ddef_pos4'], unique=False)
    op.create_index(op.f('ix_dial__defense_ddef_pos5'), 'dial__defense', ['ddef_pos5'], unique=False)
    op.create_index(op.f('ix_dial__defense_ddef_pos6'), 'dial__defense', ['ddef_pos6'], unique=False)
    op.create_index(op.f('ix_dial__defense_ddef_pos7'), 'dial__defense', ['ddef_pos7'], unique=False)
    op.create_index(op.f('ix_dial__defense_ddef_pos8'), 'dial__defense', ['ddef_pos8'], unique=False)
    op.create_index(op.f('ix_dial__defense_ddef_pos9'), 'dial__defense', ['ddef_pos9'], unique=False)
    op.create_table('dial__movement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dmov_pos1', sa.String(length=2), nullable=True),
    sa.Column('dmov_pos2', sa.String(length=2), nullable=True),
    sa.Column('dmov_pos3', sa.String(length=2), nullable=True),
    sa.Column('dmov_pos4', sa.String(length=2), nullable=True),
    sa.Column('dmov_pos5', sa.String(length=2), nullable=True),
    sa.Column('dmov_pos6', sa.String(length=2), nullable=True),
    sa.Column('dmov_pos7', sa.String(length=2), nullable=True),
    sa.Column('dmov_pos8', sa.String(length=2), nullable=True),
    sa.Column('dmov_pos9', sa.String(length=2), nullable=True),
    sa.Column('dmov_pos10', sa.String(length=2), nullable=True),
    sa.Column('dmov_pos11', sa.String(length=2), nullable=True),
    sa.Column('dmov_pos12', sa.String(length=2), nullable=True),
    sa.Column('dmov_pos13', sa.String(length=2), nullable=True),
    sa.Column('dmov_pos14', sa.String(length=2), nullable=True),
    sa.Column('dmov_pos15', sa.String(length=2), nullable=True),
    sa.Column('dmov_pos16', sa.String(length=2), nullable=True),
    sa.Column('dmov_pos17', sa.String(length=2), nullable=True),
    sa.Column('dmov_pos18', sa.String(length=2), nullable=True),
    sa.Column('dmov_pos19', sa.String(length=2), nullable=True),
    sa.Column('dmov_pos20', sa.String(length=2), nullable=True),
    sa.Column('dmov_pos21', sa.String(length=2), nullable=True),
    sa.Column('dmov_pos22', sa.String(length=2), nullable=True),
    sa.Column('dmov_pos23', sa.String(length=2), nullable=True),
    sa.Column('dmov_pos24', sa.String(length=2), nullable=True),
    sa.Column('dmov_pos25', sa.String(length=2), nullable=True),
    sa.Column('dmov_pos26', sa.String(length=2), nullable=True),
    sa.Column('dmov_cor1', sa.String(length=30), nullable=True),
    sa.Column('dmov_cor2', sa.String(length=30), nullable=True),
    sa.Column('dmov_cor3', sa.String(length=30), nullable=True),
    sa.Column('dmov_cor4', sa.String(length=30), nullable=True),
    sa.Column('dmov_cor5', sa.String(length=30), nullable=True),
    sa.Column('dmov_cor6', sa.String(length=30), nullable=True),
    sa.Column('dmov_cor7', sa.String(length=30), nullable=True),
    sa.Column('dmov_cor8', sa.String(length=30), nullable=True),
    sa.Column('dmov_cor9', sa.String(length=30), nullable=True),
    sa.Column('dmov_cor10', sa.String(length=30), nullable=True),
    sa.Column('dmov_cor11', sa.String(length=30), nullable=True),
    sa.Column('dmov_cor12', sa.String(length=30), nullable=True),
    sa.Column('dmov_cor13', sa.String(length=30), nullable=True),
    sa.Column('dmov_cor14', sa.String(length=30), nullable=True),
    sa.Column('dmov_cor15', sa.String(length=30), nullable=True),
    sa.Column('dmov_cor16', sa.String(length=30), nullable=True),
    sa.Column('dmov_cor17', sa.String(length=30), nullable=True),
    sa.Column('dmov_cor18', sa.String(length=30), nullable=True),
    sa.Column('dmov_cor19', sa.String(length=30), nullable=True),
    sa.Column('dmov_cor20', sa.String(length=30), nullable=True),
    sa.Column('dmov_cor21', sa.String(length=30), nullable=True),
    sa.Column('dmov_cor22', sa.String(length=30), nullable=True),
    sa.Column('dmov_cor23', sa.String(length=30), nullable=True),
    sa.Column('dmov_cor24', sa.String(length=30), nullable=True),
    sa.Column('dmov_cor25', sa.String(length=30), nullable=True),
    sa.Column('dmov_cor26', sa.String(length=30), nullable=True),
    sa.Column('pieces_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pieces_id'], ['pieces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dial__movement_dmov_cor1'), 'dial__movement', ['dmov_cor1'], unique=False)
    op.create_index(op.f('ix_dial__movement_dmov_cor10'), 'dial__movement', ['dmov_cor10'], unique=False)
    op.create_index(op.f('ix_dial__movement_dmov_cor11'), 'dial__movement', ['dmov_cor11'], unique=False)
    op.create_index(op.f('ix_dial__movement_dmov_cor12'), 'dial__movement', ['dmov_cor12'], unique=False)
    op.create_index(op.f('ix_dial__movement_dmov_cor13'), 'dial__movement', ['dmov_cor13'], unique=False)
    op.create_index(op.f('ix_dial__movement_dmov_cor14'), 'dial__movement', ['dmov_cor14'], unique=False)
    op.create_index(op.f('ix_dial__movement_dmov_cor15'), 'dial__movement', ['dmov_cor15'], unique=False)
    op.create_index(op.f('ix_dial__movement_dmov_cor16'), 'dial__movement', ['dmov_cor16'], unique=False)
    op.create_index(op.f('ix_dial__movement_dmov_cor17'), 'dial__movement', ['dmov_cor17'], unique=False)
    op.create_index(op.f('ix_dial__movement_dmov_cor18'), 'dial__movement', ['dmov_cor18'], unique=False)
    op.create_index(op.f('ix_dial__movement_dmov_cor19'), 'dial__movement', ['dmov_cor19'], unique=False)
    op.create_index(op.f('ix_dial__movement_dmov_cor2'), 'dial__movement', ['dmov_cor2'], unique=False)
    op.create_index(op.f('ix_dial__movement_dmov_cor20'), 'dial__movement', ['dmov_cor20'], unique=False)
    op.create_index(op.f('ix_dial__movement_dmov_cor21'), 'dial__movement', ['dmov_cor21'], unique=False)
    op.create_index(op.f('ix_dial__movement_dmov_cor22'), 'dial__movement', ['dmov_cor22'], unique=False)
    op.create_index(op.f('ix_dial__movement_dmov_cor23'), 'dial__movement', ['dmov_cor23'], unique=False)
    op.create_index(op.f('ix_dial__movement_dmov_cor24'), 'dial__movement', ['dmov_cor24'], unique=False)
    op.create_index(op.f('ix_dial__movement_dmov_cor25'), 'dial__movement', ['dmov_cor25'], unique=False)
    op.create_index(op.f('ix_dial__movement_dmov_cor26'), 'dial__movement', ['dmov_cor26'], unique=False)
    op.create_index(op.f('ix_dial__movement_dmov_cor3'), 'dial__movement', ['dmov_cor3'], unique=False)
    op.create_index(op.f('ix_dial__movement_dmov_cor4'), 'dial__movement', ['dmov_cor4'], unique=False)
    op.create_index(op.f('ix_dial__movement_dmov_cor5'), 'dial__movement', ['dmov_cor5'], unique=False)
    op.create_index(op.f('ix_dial__movement_dmov_cor6'), 'dial__movement', ['dmov_cor6'], unique=False)
    op.create_index(op.f('ix_dial__movement_dmov_cor7'), 'dial__movement', ['dmov_cor7'], unique=False)
    op.create_index(op.f('ix_dial__movement_dmov_cor8'), 'dial__movement', ['dmov_cor8'], unique=False)
    op.create_index(op.f('ix_dial__movement_dmov_cor9'), 'dial__movement', ['dmov_cor9'], unique=False)
    op.create_index(op.f('ix_dial__movement_dmov_pos1'), 'dial__movement', ['dmov_pos1'], unique=False)
    op.create_index(op.f('ix_dial__movement_dmov_pos10'), 'dial__movement', ['dmov_pos10'], unique=False)
    op.create_index(op.f('ix_dial__movement_dmov_pos11'), 'dial__movement', ['dmov_pos11'], unique=False)
    op.create_index(op.f('ix_dial__movement_dmov_pos12'), 'dial__movement', ['dmov_pos12'], unique=False)
    op.create_index(op.f('ix_dial__movement_dmov_pos13'), 'dial__movement', ['dmov_pos13'], unique=False)
    op.create_index(op.f('ix_dial__movement_dmov_pos14'), 'dial__movement', ['dmov_pos14'], unique=False)
    op.create_index(op.f('ix_dial__movement_dmov_pos15'), 'dial__movement', ['dmov_pos15'], unique=False)
    op.create_index(op.f('ix_dial__movement_dmov_pos16'), 'dial__movement', ['dmov_pos16'], unique=False)
    op.create_index(op.f('ix_dial__movement_dmov_pos17'), 'dial__movement', ['dmov_pos17'], unique=False)
    op.create_index(op.f('ix_dial__movement_dmov_pos18'), 'dial__movement', ['dmov_pos18'], unique=False)
    op.create_index(op.f('ix_dial__movement_dmov_pos19'), 'dial__movement', ['dmov_pos19'], unique=False)
    op.create_index(op.f('ix_dial__movement_dmov_pos2'), 'dial__movement', ['dmov_pos2'], unique=False)
    op.create_index(op.f('ix_dial__movement_dmov_pos20'), 'dial__movement', ['dmov_pos20'], unique=False)
    op.create_index(op.f('ix_dial__movement_dmov_pos21'), 'dial__movement', ['dmov_pos21'], unique=False)
    op.create_index(op.f('ix_dial__movement_dmov_pos22'), 'dial__movement', ['dmov_pos22'], unique=False)
    op.create_index(op.f('ix_dial__movement_dmov_pos23'), 'dial__movement', ['dmov_pos23'], unique=False)
    op.create_index(op.f('ix_dial__movement_dmov_pos24'), 'dial__movement', ['dmov_pos24'], unique=False)
    op.create_index(op.f('ix_dial__movement_dmov_pos25'), 'dial__movement', ['dmov_pos25'], unique=False)
    op.create_index(op.f('ix_dial__movement_dmov_pos26'), 'dial__movement', ['dmov_pos26'], unique=False)
    op.create_index(op.f('ix_dial__movement_dmov_pos3'), 'dial__movement', ['dmov_pos3'], unique=False)
    op.create_index(op.f('ix_dial__movement_dmov_pos4'), 'dial__movement', ['dmov_pos4'], unique=False)
    op.create_index(op.f('ix_dial__movement_dmov_pos5'), 'dial__movement', ['dmov_pos5'], unique=False)
    op.create_index(op.f('ix_dial__movement_dmov_pos6'), 'dial__movement', ['dmov_pos6'], unique=False)
    op.create_index(op.f('ix_dial__movement_dmov_pos7'), 'dial__movement', ['dmov_pos7'], unique=False)
    op.create_index(op.f('ix_dial__movement_dmov_pos8'), 'dial__movement', ['dmov_pos8'], unique=False)
    op.create_index(op.f('ix_dial__movement_dmov_pos9'), 'dial__movement', ['dmov_pos9'], unique=False)
    op.create_table('pieces_and_keywords',
    sa.Column('piece_id', sa.Integer(), nullable=False),
    sa.Column('keyword_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.id'], ),
    sa.ForeignKeyConstraint(['piece_id'], ['pieces.id'], ),
    sa.PrimaryKeyConstraint('piece_id', 'keyword_id')
    )
    op.create_table('pieces_and_traits',
    sa.Column('piece_id', sa.Integer(), nullable=False),
    sa.Column('trait_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['piece_id'], ['pieces.id'], ),
    sa.ForeignKeyConstraint(['trait_id'], ['traits.id'], ),
    sa.PrimaryKeyConstraint('piece_id', 'trait_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pieces_and_traits')
    op.drop_table('pieces_and_keywords')
    op.drop_index(op.f('ix_dial__movement_dmov_pos9'), table_name='dial__movement')
    op.drop_index(op.f('ix_dial__movement_dmov_pos8'), table_name='dial__movement')
    op.drop_index(op.f('ix_dial__movement_dmov_pos7'), table_name='dial__movement')
    op.drop_index(op.f('ix_dial__movement_dmov_pos6'), table_name='dial__movement')
    op.drop_index(op.f('ix_dial__movement_dmov_pos5'), table_name='dial__movement')
    op.drop_index(op.f('ix_dial__movement_dmov_pos4'), table_name='dial__movement')
    op.drop_index(op.f('ix_dial__movement_dmov_pos3'), table_name='dial__movement')
    op.drop_index(op.f('ix_dial__movement_dmov_pos26'), table_name='dial__movement')
    op.drop_index(op.f('ix_dial__movement_dmov_pos25'), table_name='dial__movement')
    op.drop_index(op.f('ix_dial__movement_dmov_pos24'), table_name='dial__movement')
    op.drop_index(op.f('ix_dial__movement_dmov_pos23'), table_name='dial__movement')
    op.drop_index(op.f('ix_dial__movement_dmov_pos22'), table_name='dial__movement')
    op.drop_index(op.f('ix_dial__movement_dmov_pos21'), table_name='dial__movement')
    op.drop_index(op.f('ix_dial__movement_dmov_pos20'), table_name='dial__movement')
    op.drop_index(op.f('ix_dial__movement_dmov_pos2'), table_name='dial__movement')
    op.drop_index(op.f('ix_dial__movement_dmov_pos19'), table_name='dial__movement')
    op.drop_index(op.f('ix_dial__movement_dmov_pos18'), table_name='dial__movement')
    op.drop_index(op.f('ix_dial__movement_dmov_pos17'), table_name='dial__movement')
    op.drop_index(op.f('ix_dial__movement_dmov_pos16'), table_name='dial__movement')
    op.drop_index(op.f('ix_dial__movement_dmov_pos15'), table_name='dial__movement')
    op.drop_index(op.f('ix_dial__movement_dmov_pos14'), table_name='dial__movement')
    op.drop_index(op.f('ix_dial__movement_dmov_pos13'), table_name='dial__movement')
    op.drop_index(op.f('ix_dial__movement_dmov_pos12'), table_name='dial__movement')
    op.drop_index(op.f('ix_dial__movement_dmov_pos11'), table_name='dial__movement')
    op.drop_index(op.f('ix_dial__movement_dmov_pos10'), table_name='dial__movement')
    op.drop_index(op.f('ix_dial__movement_dmov_pos1'), table_name='dial__movement')
    op.drop_index(op.f('ix_dial__movement_dmov_cor9'), table_name='dial__movement')
    op.drop_index(op.f('ix_dial__movement_dmov_cor8'), table_name='dial__movement')
    op.drop_index(op.f('ix_dial__movement_dmov_cor7'), table_name='dial__movement')
    op.drop_index(op.f('ix_dial__movement_dmov_cor6'), table_name='dial__movement')
    op.drop_index(op.f('ix_dial__movement_dmov_cor5'), table_name='dial__movement')
    op.drop_index(op.f('ix_dial__movement_dmov_cor4'), table_name='dial__movement')
    op.drop_index(op.f('ix_dial__movement_dmov_cor3'), table_name='dial__movement')
    op.drop_index(op.f('ix_dial__movement_dmov_cor26'), table_name='dial__movement')
    op.drop_index(op.f('ix_dial__movement_dmov_cor25'), table_name='dial__movement')
    op.drop_index(op.f('ix_dial__movement_dmov_cor24'), table_name='dial__movement')
    op.drop_index(op.f('ix_dial__movement_dmov_cor23'), table_name='dial__movement')
    op.drop_index(op.f('ix_dial__movement_dmov_cor22'), table_name='dial__movement')
    op.drop_index(op.f('ix_dial__movement_dmov_cor21'), table_name='dial__movement')
    op.drop_index(op.f('ix_dial__movement_dmov_cor20'), table_name='dial__movement')
    op.drop_index(op.f('ix_dial__movement_dmov_cor2'), table_name='dial__movement')
    op.drop_index(op.f('ix_dial__movement_dmov_cor19'), table_name='dial__movement')
    op.drop_index(op.f('ix_dial__movement_dmov_cor18'), table_name='dial__movement')
    op.drop_index(op.f('ix_dial__movement_dmov_cor17'), table_name='dial__movement')
    op.drop_index(op.f('ix_dial__movement_dmov_cor16'), table_name='dial__movement')
    op.drop_index(op.f('ix_dial__movement_dmov_cor15'), table_name='dial__movement')
    op.drop_index(op.f('ix_dial__movement_dmov_cor14'), table_name='dial__movement')
    op.drop_index(op.f('ix_dial__movement_dmov_cor13'), table_name='dial__movement')
    op.drop_index(op.f('ix_dial__movement_dmov_cor12'), table_name='dial__movement')
    op.drop_index(op.f('ix_dial__movement_dmov_cor11'), table_name='dial__movement')
    op.drop_index(op.f('ix_dial__movement_dmov_cor10'), table_name='dial__movement')
    op.drop_index(op.f('ix_dial__movement_dmov_cor1'), table_name='dial__movement')
    op.drop_table('dial__movement')
    op.drop_index(op.f('ix_dial__defense_ddef_pos9'), table_name='dial__defense')
    op.drop_index(op.f('ix_dial__defense_ddef_pos8'), table_name='dial__defense')
    op.drop_index(op.f('ix_dial__defense_ddef_pos7'), table_name='dial__defense')
    op.drop_index(op.f('ix_dial__defense_ddef_pos6'), table_name='dial__defense')
    op.drop_index(op.f('ix_dial__defense_ddef_pos5'), table_name='dial__defense')
    op.drop_index(op.f('ix_dial__defense_ddef_pos4'), table_name='dial__defense')
    op.drop_index(op.f('ix_dial__defense_ddef_pos3'), table_name='dial__defense')
    op.drop_index(op.f('ix_dial__defense_ddef_pos26'), table_name='dial__defense')
    op.drop_index(op.f('ix_dial__defense_ddef_pos25'), table_name='dial__defense')
    op.drop_index(op.f('ix_dial__defense_ddef_pos24'), table_name='dial__defense')
    op.drop_index(op.f('ix_dial__defense_ddef_pos23'), table_name='dial__defense')
    op.drop_index(op.f('ix_dial__defense_ddef_pos22'), table_name='dial__defense')
    op.drop_index(op.f('ix_dial__defense_ddef_pos21'), table_name='dial__defense')
    op.drop_index(op.f('ix_dial__defense_ddef_pos20'), table_name='dial__defense')
    op.drop_index(op.f('ix_dial__defense_ddef_pos2'), table_name='dial__defense')
    op.drop_index(op.f('ix_dial__defense_ddef_pos19'), table_name='dial__defense')
    op.drop_index(op.f('ix_dial__defense_ddef_pos18'), table_name='dial__defense')
    op.drop_index(op.f('ix_dial__defense_ddef_pos17'), table_name='dial__defense')
    op.drop_index(op.f('ix_dial__defense_ddef_pos16'), table_name='dial__defense')
    op.drop_index(op.f('ix_dial__defense_ddef_pos15'), table_name='dial__defense')
    op.drop_index(op.f('ix_dial__defense_ddef_pos14'), table_name='dial__defense')
    op.drop_index(op.f('ix_dial__defense_ddef_pos13'), table_name='dial__defense')
    op.drop_index(op.f('ix_dial__defense_ddef_pos12'), table_name='dial__defense')
    op.drop_index(op.f('ix_dial__defense_ddef_pos11'), table_name='dial__defense')
    op.drop_index(op.f('ix_dial__defense_ddef_pos10'), table_name='dial__defense')
    op.drop_index(op.f('ix_dial__defense_ddef_pos1'), table_name='dial__defense')
    op.drop_index(op.f('ix_dial__defense_ddef_cor9'), table_name='dial__defense')
    op.drop_index(op.f('ix_dial__defense_ddef_cor8'), table_name='dial__defense')
    op.drop_index(op.f('ix_dial__defense_ddef_cor7'), table_name='dial__defense')
    op.drop_index(op.f('ix_dial__defense_ddef_cor6'), table_name='dial__defense')
    op.drop_index(op.f('ix_dial__defense_ddef_cor5'), table_name='dial__defense')
    op.drop_index(op.f('ix_dial__defense_ddef_cor4'), table_name='dial__defense')
    op.drop_index(op.f('ix_dial__defense_ddef_cor3'), table_name='dial__defense')
    op.drop_index(op.f('ix_dial__defense_ddef_cor26'), table_name='dial__defense')
    op.drop_index(op.f('ix_dial__defense_ddef_cor25'), table_name='dial__defense')
    op.drop_index(op.f('ix_dial__defense_ddef_cor24'), table_name='dial__defense')
    op.drop_index(op.f('ix_dial__defense_ddef_cor23'), table_name='dial__defense')
    op.drop_index(op.f('ix_dial__defense_ddef_cor22'), table_name='dial__defense')
    op.drop_index(op.f('ix_dial__defense_ddef_cor21'), table_name='dial__defense')
    op.drop_index(op.f('ix_dial__defense_ddef_cor20'), table_name='dial__defense')
    op.drop_index(op.f('ix_dial__defense_ddef_cor2'), table_name='dial__defense')
    op.drop_index(op.f('ix_dial__defense_ddef_cor19'), table_name='dial__defense')
    op.drop_index(op.f('ix_dial__defense_ddef_cor18'), table_name='dial__defense')
    op.drop_index(op.f('ix_dial__defense_ddef_cor17'), table_name='dial__defense')
    op.drop_index(op.f('ix_dial__defense_ddef_cor16'), table_name='dial__defense')
    op.drop_index(op.f('ix_dial__defense_ddef_cor15'), table_name='dial__defense')
    op.drop_index(op.f('ix_dial__defense_ddef_cor14'), table_name='dial__defense')
    op.drop_index(op.f('ix_dial__defense_ddef_cor13'), table_name='dial__defense')
    op.drop_index(op.f('ix_dial__defense_ddef_cor12'), table_name='dial__defense')
    op.drop_index(op.f('ix_dial__defense_ddef_cor11'), table_name='dial__defense')
    op.drop_index(op.f('ix_dial__defense_ddef_cor10'), table_name='dial__defense')
    op.drop_index(op.f('ix_dial__defense_ddef_cor1'), table_name='dial__defense')
    op.drop_table('dial__defense')
    op.drop_index(op.f('ix_dial__damage_ddam_pos9'), table_name='dial__damage')
    op.drop_index(op.f('ix_dial__damage_ddam_pos8'), table_name='dial__damage')
    op.drop_index(op.f('ix_dial__damage_ddam_pos7'), table_name='dial__damage')
    op.drop_index(op.f('ix_dial__damage_ddam_pos6'), table_name='dial__damage')
    op.drop_index(op.f('ix_dial__damage_ddam_pos5'), table_name='dial__damage')
    op.drop_index(op.f('ix_dial__damage_ddam_pos4'), table_name='dial__damage')
    op.drop_index(op.f('ix_dial__damage_ddam_pos3'), table_name='dial__damage')
    op.drop_index(op.f('ix_dial__damage_ddam_pos26'), table_name='dial__damage')
    op.drop_index(op.f('ix_dial__damage_ddam_pos25'), table_name='dial__damage')
    op.drop_index(op.f('ix_dial__damage_ddam_pos24'), table_name='dial__damage')
    op.drop_index(op.f('ix_dial__damage_ddam_pos23'), table_name='dial__damage')
    op.drop_index(op.f('ix_dial__damage_ddam_pos22'), table_name='dial__damage')
    op.drop_index(op.f('ix_dial__damage_ddam_pos21'), table_name='dial__damage')
    op.drop_index(op.f('ix_dial__damage_ddam_pos20'), table_name='dial__damage')
    op.drop_index(op.f('ix_dial__damage_ddam_pos2'), table_name='dial__damage')
    op.drop_index(op.f('ix_dial__damage_ddam_pos19'), table_name='dial__damage')
    op.drop_index(op.f('ix_dial__damage_ddam_pos18'), table_name='dial__damage')
    op.drop_index(op.f('ix_dial__damage_ddam_pos17'), table_name='dial__damage')
    op.drop_index(op.f('ix_dial__damage_ddam_pos16'), table_name='dial__damage')
    op.drop_index(op.f('ix_dial__damage_ddam_pos15'), table_name='dial__damage')
    op.drop_index(op.f('ix_dial__damage_ddam_pos14'), table_name='dial__damage')
    op.drop_index(op.f('ix_dial__damage_ddam_pos13'), table_name='dial__damage')
    op.drop_index(op.f('ix_dial__damage_ddam_pos12'), table_name='dial__damage')
    op.drop_index(op.f('ix_dial__damage_ddam_pos11'), table_name='dial__damage')
    op.drop_index(op.f('ix_dial__damage_ddam_pos10'), table_name='dial__damage')
    op.drop_index(op.f('ix_dial__damage_ddam_pos1'), table_name='dial__damage')
    op.drop_index(op.f('ix_dial__damage_ddam_cor9'), table_name='dial__damage')
    op.drop_index(op.f('ix_dial__damage_ddam_cor8'), table_name='dial__damage')
    op.drop_index(op.f('ix_dial__damage_ddam_cor7'), table_name='dial__damage')
    op.drop_index(op.f('ix_dial__damage_ddam_cor6'), table_name='dial__damage')
    op.drop_index(op.f('ix_dial__damage_ddam_cor5'), table_name='dial__damage')
    op.drop_index(op.f('ix_dial__damage_ddam_cor4'), table_name='dial__damage')
    op.drop_index(op.f('ix_dial__damage_ddam_cor3'), table_name='dial__damage')
    op.drop_index(op.f('ix_dial__damage_ddam_cor26'), table_name='dial__damage')
    op.drop_index(op.f('ix_dial__damage_ddam_cor25'), table_name='dial__damage')
    op.drop_index(op.f('ix_dial__damage_ddam_cor24'), table_name='dial__damage')
    op.drop_index(op.f('ix_dial__damage_ddam_cor23'), table_name='dial__damage')
    op.drop_index(op.f('ix_dial__damage_ddam_cor22'), table_name='dial__damage')
    op.drop_index(op.f('ix_dial__damage_ddam_cor21'), table_name='dial__damage')
    op.drop_index(op.f('ix_dial__damage_ddam_cor20'), table_name='dial__damage')
    op.drop_index(op.f('ix_dial__damage_ddam_cor2'), table_name='dial__damage')
    op.drop_index(op.f('ix_dial__damage_ddam_cor19'), table_name='dial__damage')
    op.drop_index(op.f('ix_dial__damage_ddam_cor18'), table_name='dial__damage')
    op.drop_index(op.f('ix_dial__damage_ddam_cor17'), table_name='dial__damage')
    op.drop_index(op.f('ix_dial__damage_ddam_cor16'), table_name='dial__damage')
    op.drop_index(op.f('ix_dial__damage_ddam_cor15'), table_name='dial__damage')
    op.drop_index(op.f('ix_dial__damage_ddam_cor14'), table_name='dial__damage')
    op.drop_index(op.f('ix_dial__damage_ddam_cor13'), table_name='dial__damage')
    op.drop_index(op.f('ix_dial__damage_ddam_cor12'), table_name='dial__damage')
    op.drop_index(op.f('ix_dial__damage_ddam_cor11'), table_name='dial__damage')
    op.drop_index(op.f('ix_dial__damage_ddam_cor10'), table_name='dial__damage')
    op.drop_index(op.f('ix_dial__damage_ddam_cor1'), table_name='dial__damage')
    op.drop_table('dial__damage')
    op.drop_index(op.f('ix_dial__attack_datk_pos9'), table_name='dial__attack')
    op.drop_index(op.f('ix_dial__attack_datk_pos8'), table_name='dial__attack')
    op.drop_index(op.f('ix_dial__attack_datk_pos7'), table_name='dial__attack')
    op.drop_index(op.f('ix_dial__attack_datk_pos6'), table_name='dial__attack')
    op.drop_index(op.f('ix_dial__attack_datk_pos5'), table_name='dial__attack')
    op.drop_index(op.f('ix_dial__attack_datk_pos4'), table_name='dial__attack')
    op.drop_index(op.f('ix_dial__attack_datk_pos3'), table_name='dial__attack')
    op.drop_index(op.f('ix_dial__attack_datk_pos26'), table_name='dial__attack')
    op.drop_index(op.f('ix_dial__attack_datk_pos25'), table_name='dial__attack')
    op.drop_index(op.f('ix_dial__attack_datk_pos24'), table_name='dial__attack')
    op.drop_index(op.f('ix_dial__attack_datk_pos23'), table_name='dial__attack')
    op.drop_index(op.f('ix_dial__attack_datk_pos22'), table_name='dial__attack')
    op.drop_index(op.f('ix_dial__attack_datk_pos21'), table_name='dial__attack')
    op.drop_index(op.f('ix_dial__attack_datk_pos20'), table_name='dial__attack')
    op.drop_index(op.f('ix_dial__attack_datk_pos2'), table_name='dial__attack')
    op.drop_index(op.f('ix_dial__attack_datk_pos19'), table_name='dial__attack')
    op.drop_index(op.f('ix_dial__attack_datk_pos18'), table_name='dial__attack')
    op.drop_index(op.f('ix_dial__attack_datk_pos17'), table_name='dial__attack')
    op.drop_index(op.f('ix_dial__attack_datk_pos16'), table_name='dial__attack')
    op.drop_index(op.f('ix_dial__attack_datk_pos15'), table_name='dial__attack')
    op.drop_index(op.f('ix_dial__attack_datk_pos14'), table_name='dial__attack')
    op.drop_index(op.f('ix_dial__attack_datk_pos13'), table_name='dial__attack')
    op.drop_index(op.f('ix_dial__attack_datk_pos12'), table_name='dial__attack')
    op.drop_index(op.f('ix_dial__attack_datk_pos11'), table_name='dial__attack')
    op.drop_index(op.f('ix_dial__attack_datk_pos10'), table_name='dial__attack')
    op.drop_index(op.f('ix_dial__attack_datk_pos1'), table_name='dial__attack')
    op.drop_index(op.f('ix_dial__attack_datk_cor9'), table_name='dial__attack')
    op.drop_index(op.f('ix_dial__attack_datk_cor8'), table_name='dial__attack')
    op.drop_index(op.f('ix_dial__attack_datk_cor7'), table_name='dial__attack')
    op.drop_index(op.f('ix_dial__attack_datk_cor6'), table_name='dial__attack')
    op.drop_index(op.f('ix_dial__attack_datk_cor5'), table_name='dial__attack')
    op.drop_index(op.f('ix_dial__attack_datk_cor4'), table_name='dial__attack')
    op.drop_index(op.f('ix_dial__attack_datk_cor3'), table_name='dial__attack')
    op.drop_index(op.f('ix_dial__attack_datk_cor26'), table_name='dial__attack')
    op.drop_index(op.f('ix_dial__attack_datk_cor25'), table_name='dial__attack')
    op.drop_index(op.f('ix_dial__attack_datk_cor24'), table_name='dial__attack')
    op.drop_index(op.f('ix_dial__attack_datk_cor23'), table_name='dial__attack')
    op.drop_index(op.f('ix_dial__attack_datk_cor22'), table_name='dial__attack')
    op.drop_index(op.f('ix_dial__attack_datk_cor21'), table_name='dial__attack')
    op.drop_index(op.f('ix_dial__attack_datk_cor20'), table_name='dial__attack')
    op.drop_index(op.f('ix_dial__attack_datk_cor2'), table_name='dial__attack')
    op.drop_index(op.f('ix_dial__attack_datk_cor19'), table_name='dial__attack')
    op.drop_index(op.f('ix_dial__attack_datk_cor18'), table_name='dial__attack')
    op.drop_index(op.f('ix_dial__attack_datk_cor17'), table_name='dial__attack')
    op.drop_index(op.f('ix_dial__attack_datk_cor16'), table_name='dial__attack')
    op.drop_index(op.f('ix_dial__attack_datk_cor15'), table_name='dial__attack')
    op.drop_index(op.f('ix_dial__attack_datk_cor14'), table_name='dial__attack')
    op.drop_index(op.f('ix_dial__attack_datk_cor13'), table_name='dial__attack')
    op.drop_index(op.f('ix_dial__attack_datk_cor12'), table_name='dial__attack')
    op.drop_index(op.f('ix_dial__attack_datk_cor11'), table_name='dial__attack')
    op.drop_index(op.f('ix_dial__attack_datk_cor10'), table_name='dial__attack')
    op.drop_index(op.f('ix_dial__attack_datk_cor1'), table_name='dial__attack')
    op.drop_table('dial__attack')
    op.drop_index(op.f('ix_pieces_piece_real_name'), table_name='pieces')
    op.drop_index(op.f('ix_pieces_piece_rarity'), table_name='pieces')
    op.drop_index(op.f('ix_pieces_piece_point'), table_name='pieces')
    op.drop_index(op.f('ix_pieces_piece_number'), table_name='pieces')
    op.drop_index(op.f('ix_pieces_piece_name'), table_name='pieces')
    op.drop_index(op.f('ix_pieces_piece_mov_type'), table_name='pieces')
    op.drop_index(op.f('ix_pieces_piece_improved_target'), table_name='pieces')
    op.drop_index(op.f('ix_pieces_piece_improved_mov'), table_name='pieces')
    op.drop_index(op.f('ix_pieces_piece_def_type'), table_name='pieces')
    op.drop_index(op.f('ix_pieces_piece_dam_type'), table_name='pieces')
    op.drop_index(op.f('ix_pieces_piece_atk_type'), table_name='pieces')
    op.drop_table('pieces')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_traits_trait_name'), table_name='traits')
    op.drop_index(op.f('ix_traits_trait_description'), table_name='traits')
    op.drop_table('traits')
    op.drop_index(op.f('ix_keywords_key_name'), table_name='keywords')
    op.drop_table('keywords')
    op.drop_index(op.f('ix_collection_colle_name'), table_name='collection')
    op.drop_index(op.f('ix_collection_colle_initials'), table_name='collection')
    op.drop_index(op.f('ix_collection_colle_age'), table_name='collection')
    op.drop_table('collection')
    # ### end Alembic commands ###
